.github/workflows/report_ram_log.yml
.github/workflows/tpch.yml

[NSE-11] Fix RAM usage CI

---

core/src/main/scala/com/intel/oap/expression/ColumnarSortMergeJoin.scala
core/src/main/scala/com/intel/oap/expression/ColumnarSorter.scala

[NSE-15]fix unexpected exception

---

README.md

[NSE-8]fix doc

---

core/src/main/scala/com/intel/oap/execution/ColumnarSortMergeJoinExec.scala

[NSE-23]fix columnar SMJ fallback

---

core/src/main/scala/com/intel/oap/execution/ColumnarWholeStageCodegenExec.scala

[NSE-1]fix columnar wscg on empty recordbatch

---

core/src/main/java/com/intel/oap/vectorized/ShuffleSplitterJniWrapper.java
core/src/main/scala/org/apache/spark/shuffle/ColumnarShuffleWriter.scala
cpp/src/jni/jni_wrapper.cc
cpp/src/shuffle/splitter.cc
cpp/src/shuffle/splitter.h

[NSE-32] Use Spark managed spill in columnar shuffle

---

.github/workflows/dev_cron.yml
.github/workflows/dev_cron/issues_link.js
.github/workflows/dev_cron/title_check.js
.github/workflows/dev_cron/title_check.md

Modify title check and automatic link to Issues for PRs.
Fix: #114 
Actions passed.

[NSE-114]Modify title check and automatic link to Issues for PRs

---

.github/workflows/report_ram_log.yml
.github/workflows/tpch.yml
.github/workflows/unittests.yml

This patch changes to use arrow-data-source under oap-project
Fixes: #139 
Unit tests

[NSE-139]fix CI with oap-project/arrow-data-source

---

native-sql-engine/cpp/src/codegen/arrow_compute/ext/codegen_node_visitor.cc

this patches adds decimal support for SMJ
related: #31

[NSE-31] fix SMJ divide with decimal

---

native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarWindowExec.scala
native-sql-engine/cpp/src/codegen/arrow_compute/ext/window_sort_kernel.h

This patch fixes window results
fixes: https://github.com/oap-project/native-sql-engine/issues/153

[NSE-153] fix window results

---

native-sql-engine/cpp/src/CMakeLists.txt

Close #180 
Done by my developing server.

[NSE-179]Fix arrow include directory not include when using ARROW_ROOT

---

arrow-data-source/standard/src/main/scala/com/intel/oap/spark/sql/execution/datasources/v2/arrow/ArrowUtils.scala
native-sql-engine/core/src/test/scala/com/intel/oap/tpc/ds/TPCDSSuite.scala
native-sql-engine/core/src/test/scala/com/intel/oap/tpc/ds/TPCDSTableGen.scala

[NSE-211] IndexOutOfBoundsException during running TPC-DS Q2

---

native-sql-engine/cpp/src/CMakeLists.txt

bump protobuf version to 3.13.0

[NSE-213] upgrade protobuf to 3.13.0

---

arrow-data-source/standard/src/main/scala/com/intel/oap/spark/sql/execution/datasources/v2/arrow/ArrowUtils.scala
native-sql-engine/core/src/main/java/com/intel/oap/datasource/parquet/ParquetReader.java
native-sql-engine/core/src/main/java/com/intel/oap/vectorized/JniUtils.java
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarConditionProjector.scala
native-sql-engine/core/src/test/scala/com/intel/oap/tpc/ds/TPCDSSuite.scala
native-sql-engine/core/src/test/scala/com/intel/oap/tpc/ds/TPCDSTableGen.scala
native-sql-engine/cpp/src/codegen/arrow_compute/code_generator.h
native-sql-engine/cpp/src/codegen/arrow_compute/ext/basic_physical_kernels.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/codegen_common.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/codegen_node_visitor.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/conditioned_merge_join_kernel.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/conditioned_probe_kernel.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/expression_codegen_visitor.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/hash_aggregate_kernel.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/hash_relation_kernel.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/kernels_ext.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/kernels_ext.h
native-sql-engine/cpp/src/codegen/arrow_compute/ext/merge_join_kernel.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/probe_kernel.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/sort_kernel.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/whole_stage_codegen_kernel.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/window_kernel.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/window_sort_kernel.h
native-sql-engine/cpp/src/codegen/expr_visitor.h
native-sql-engine/cpp/src/jni/jni_wrapper.cc
native-sql-engine/cpp/src/precompile/array.cc
native-sql-engine/cpp/src/precompile/gandiva.h
native-sql-engine/cpp/src/precompile/hash_arrays_kernel.cc
native-sql-engine/cpp/src/shuffle/splitter.cc

backport recent changes to 1.1 branch

[NSE-186]backport 1.1 batch2

---

native-sql-engine/cpp/src/codegen/arrow_compute/ext/actions_impl.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/hash_aggregate_kernel.cc

do not shadow the length param in hashagg output
under test

[NSE-241] fix hashagg result length

---

arrow-data-source/pom.xml
native-sql-engine/core/pom.xml

fixed: https://github.com/oap-project/native-sql-engine/issues/257
locally tested

[NSE-257] fix different versions of slf4j-log4j12

---

arrow-data-source/script/build_arrow.sh

1.1 branch should use arrow-3.0.0-oap-1.1

[NSE-278]fix arrow dep in 1.1 branch

---

native-sql-engine/cpp/CMakeLists.txt
native-sql-engine/cpp/src/CMakeLists.txt

bump CMake to 3.16
fixes: #280 

[NSE-280] bump cmake to 3.16

---

native-sql-engine/cpp/CMakeLists.txt
native-sql-engine/cpp/src/CMakeLists.txt

bump CMake to 3.16
fixes: #280
Signed-off-by: Yuan Zhou yuan.zhou@intel.com

[NSE-280]fix cmake version check

---

docs/ApacheArrowInstallation.md
docs/Prerequisite.md

Close #206 
Document Update Only

[NSE-206]Fix Prerequisite and Arrow Installation Steps.

---

native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarHashAggregation.scala

This pr removes the exception in v2 test.
fixed: https://github.com/oap-project/native-sql-engine/issues/302
verified on TPC-DS v2/v1

[NSE-302] fix v2 test

---

arrow-data-source/pom.xml

fixed: https://github.com/oap-project/native-sql-engine/issues/257
locally tested

[NSE-257] fix the dependency issue on v2

---

arrow-data-source/common/pom.xml
arrow-data-source/parquet/pom.xml
arrow-data-source/pom.xml
arrow-data-source/standard/pom.xml
native-sql-engine/core/pom.xml
pom.xml

[NSE-305] bump version to 1.2.0-snapshot

---

native-sql-engine/core/src/main/scala/org/apache/spark/sql/execution/adaptive/AdaptiveSparkPlanExec.scala

[NSE-318]check schema before reuse exchange

---

.github/workflows/tpch.yml
.github/workflows/unittests.yml
arrow-data-source/README.md
arrow-data-source/common/pom.xml
arrow-data-source/common/src/main/java/com/intel/oap/spark/sql/execution/datasources/v2/arrow/SparkManagedReservationListener.java
arrow-data-source/parquet/pom.xml
arrow-data-source/pom.xml
arrow-data-source/script/build_arrow.sh
arrow-data-source/standard/pom.xml
arrow-data-source/standard/src/main/scala/com/intel/oap/spark/sql/execution/datasources/arrow/ArrowFileFormat.scala
arrow-data-source/standard/src/main/scala/com/intel/oap/spark/sql/execution/datasources/v2/arrow/ArrowPartitionReaderFactory.scala
arrow-data-source/standard/src/main/scala/com/intel/oap/spark/sql/execution/datasources/v2/arrow/ArrowUtils.scala
docs/ApacheArrowInstallation.md
docs/OAP-Developer-Guide.md
docs/OAP-Installation-Guide.md
mkdocs.yml
native-sql-engine/core/pom.xml
native-sql-engine/core/src/main/java/com/intel/oap/vectorized/JniUtils.java
native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarBroadcastHashJoinExec.scala
native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarShuffledHashJoinExec.scala
native-sql-engine/core/src/main/scala/org/apache/spark/sql/execution/adaptive/AdaptiveSparkPlanExec.scala
native-sql-engine/cpp/src/CMakeLists.txt
native-sql-engine/cpp/src/codegen/arrow_compute/ext/kernels_ext.h
native-sql-engine/cpp/src/codegen/common/visitor_base.h
pom.xml

backport spark 311 support to 1.1.1 branch

[NSE-273] backport spark311 support to 1.1.1 branch

---

native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarWholeStageCodegenExec.scala
native-sql-engine/core/src/test/scala/com/intel/oap/tpc/ds/TPCDSSuite.scala
native-sql-engine/core/src/test/scala/com/intel/oap/tpc/h/TPCHSuite.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/JoinSuite.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/execution/joins/ExistenceJoinSuite.scala
native-sql-engine/cpp/src/codegen/arrow_compute/ext/conditioned_probe_kernel.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/expression_codegen_visitor.cc
native-sql-engine/cpp/src/precompile/gandiva.h
native-sql-engine/cpp/src/tests/arrow_compute_test_join_wocg.cc
native-sql-engine/cpp/src/tests/arrow_compute_test_wscg.cc
native-sql-engine/tools/run_ut.sh

depends on: https://github.com/oap-project/arrow/pull/13
https://github.com/oap-project/native-sql-engine/issues/207
verified on TPC-DS v2 and v1

[NSE-207] fix issues found from join unit tests

---

CHANGELOG.md
arrow-data-source/README.md
docs/Installation.md
docs/OAP-Developer-Guide.md
docs/OAP-Installation-Guide.md
docs/Prerequisite.md
docs/SparkInstallation.md
docs/User-Guide.md
docs/index.md

Update the documents for 1.1.1
N/A

[NSE-350]Update the documents for 1.1.1

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

update github issue templates
fixes: #377 

[NSE-377] update github issues template

---

README.md
docs/ApacheArrowInstallation.md
docs/Configuration.md
docs/Installation.md
docs/OAP-Developer-Guide.md
docs/SparkInstallation.md
docs/User-Guide.md
docs/index.md
docs/limitations.md
docs/memory.md
mkdocs.yml

Modify repo name in documents.

[NSE-404]Modify repo name in documents

---

README.md

Add Dataproc integration section to README,  it will redirect to a detailed guide and related scripts on oap-tools.

[NSE-403]Add Dataproc integration section to README

---

.github/workflows/unittests.yml
native-sql-engine/cpp/src/CMakeLists.txt

this patch adds ccache support for c++ code compile
N/A

[NSE-411] adding ccache support

---

arrow-data-source/standard/pom.xml
native-sql-engine/core/pom.xml
pom.xml

To upgrade maven assembly plugin version to 3.3.0 and maven jar plugin version to 3.2.0.
This version upgrade can help to solve symlink issue as well as reduce jar size.
Tested in local server

[NSE-254]Solve the redundant arrow library issue

---

arrow-data-source/standard/pom.xml
native-sql-engine/core/pom.xml
pom.xml

Update maven assemble plugin to 3.3.0
Remove maven jar plugin 3.2.0
Tested in local server

[NSE-254]Issue0410 jar size

---

native-sql-engine/core/pom.xml
native-sql-engine/core/src/main/java/com/intel/oap/vectorized/JniUtils.java
native-sql-engine/cpp/src/CMakeLists.txt
pom.xml

backport master code to 1.2 branch

[NSE-451] backport master code to 1.2 branch

---

.github/workflows/tpch.yml
.github/workflows/unittests.yml
arrow-data-source/common/pom.xml
arrow-data-source/parquet/pom.xml
arrow-data-source/pom.xml
arrow-data-source/script/build_arrow.sh
arrow-data-source/standard/pom.xml
native-sql-engine/core/pom.xml
pom.xml
shims/common/pom.xml
shims/pom.xml
shims/spark311/pom.xml

bump version in 1.2 branch, also fixed to use correct arrow branch. 

[NSE-451] branch 1.2 version update

---

native-sql-engine/core/src/main/scala/com/intel/oap/ColumnarPlugin.scala

Support ArrowColumnarToRowExec when the root plan is ColumnarToRowExec
existing tests

[NSE-444]Support ArrowColumnarToRowExec when the root plan is ColumnarToRowExec

---

native-sql-engine/core/pom.xml

https://github.com/oap-project/gazelle_plugin/issues/207
verified on Jenkins

[NSE-207] Enabling UT report

---

native-sql-engine/cpp/src/codegen/arrow_compute/ext/sort_kernel.cc

This pr added a new codegen kernel in sort, and removed previous codegen codes in base class.
fixed: https://github.com/oap-project/gazelle_plugin/issues/449
verified on TPC-DS v1 and v2

[NSE-449] Refactor codegen sort kernel

---

native-sql-engine/core/src/main/java/com/intel/oap/execution/ColumnarNativeIterator.java
native-sql-engine/core/src/main/java/com/intel/oap/vectorized/ExpressionEvaluator.java
native-sql-engine/core/src/main/java/com/intel/oap/vectorized/ExpressionEvaluatorJniWrapper.java
native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarWholeStageCodegenExec.scala
native-sql-engine/cpp/src/jni/jni_wrapper.cc

[NSE-469] Lazy Read: Iterator objects are not correctly released

---

native-sql-engine/core/src/main/java/com/intel/oap/execution/ColumnarNativeIterator.java
native-sql-engine/core/src/main/java/com/intel/oap/vectorized/ExpressionEvaluator.java
native-sql-engine/core/src/main/java/com/intel/oap/vectorized/ExpressionEvaluatorJniWrapper.java
native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarWholeStageCodegenExec.scala
native-sql-engine/cpp/src/jni/jni_wrapper.cc

* [NSE-469] Lazy Read: Iterator objects are not correctly released
* style
* debugging
* debugging
* fixup

[NSE-451] backport master to 1.2 

---

arrow-data-source/common/src/main/java/com/intel/oap/spark/sql/execution/datasources/v2/arrow/SparkManagedReservationListener.java
arrow-data-source/common/src/main/scala/org/apache/spark/sql/execution/datasources/v2/arrow/SparkMemoryUtils.scala

* [NSE-481] JVM heap memory leak on memory leak tracker facilities
* fixup
* fixup

[NSE-451] backport master to 1.2 branch

---

arrow-data-source/common/src/main/java/com/intel/oap/vectorized/ArrowWritableColumnVector.java
arrow-data-source/common/src/main/scala/com/intel/oap/sql/execution/RowToArrowColumnarExec.scala
native-sql-engine/core/src/main/scala/org/apache/spark/sql/execution/ColumnarShuffleExchangeExec.scala
native-sql-engine/core/src/main/scala/org/apache/spark/sql/execution/python/ColumnarArrowEvalPythonExec.scala
native-sql-engine/core/src/main/scala/org/apache/spark/sql/execution/python/ColumnarArrowPythonRunner.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/IntegratedUDFTestUtils.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/execution/python/ArrowEvalPythonExecSuite.scala

Fixed: https://github.com/oap-project/gazelle_plugin/issues/461

[NSE-461][WIP] Support ArrayType in ArrowWritableColumnVector and ColumarPandasUDF

---

CHANGELOG.md
README.md
docs/OAP-Developer-Guide.md
docs/OAP-Installation-Guide.md
docs/index.md

Update Changelog and OAP guide.
N/A

[NSE-498] Update Changelog and OAP guide

---

native-sql-engine/core/src/test/scala/com/intel/oap/tpc/ds/TPCDSSuite.scala

This patch includes just trivial change. Going to merge in advance.

[NSE-504] Fix non-decimal window function unit test

---

native-sql-engine/cpp/src/tests/CMakeLists.txt

Previous PR removed this UT, fix here

---

native-sql-engine/tools/failed_ut_list.log
native-sql-engine/tools/run_ut.sh

This pr fixes the UT test on Jenkins.
https://github.com/oap-project/gazelle_plugin/issues/207
verified on Jenkins

[NSE-207] fix full UT test

---

arrow-data-source/standard/src/main/scala/com/intel/oap/spark/sql/ArrowWriteExtension.scala

This PR is aim to support AQE enable for ColumnarWriter, and has tested by Chendi
Fixed: https://github.com/oap-project/gazelle_plugin/issues/525

[NSE-525]Support AQE for ColumnarWriter

---

native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarBinaryExpression.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarDateTimeExpressions.scala

This patch implements columnar from_unixtime
closes: #572 
unit tests

[NSE-576] implement columnar from_unixtime

---

native-sql-engine/core/src/test/scala/com/intel/oap/tpc/ds/Orc_TPCDSSuite.scala
native-sql-engine/core/src/test/scala/com/intel/oap/tpc/ds/Orc_TPCDSTableGen.scala
native-sql-engine/core/src/test/scala/com/intel/oap/tpc/h/Orc_TPCHSuite.scala
native-sql-engine/core/src/test/scala/com/intel/oap/tpc/h/Orc_TPCHTableGen.scala

This patch adds ORC based TPCH/TPCDS tests
unit tests

[NSE-589] Add TPCDS and TPCH suite for Orc fileformat

---

arrow-data-source/standard/src/test/scala/com/intel/oap/spark/sql/execution/datasources/arrow/ArrowDataSourceTest.scala
native-sql-engine/core/src/test/scala/com/intel/oap/tpc/h/Orc_TPCHSuite.scala

1. Add complex data types validation UTs
2. In addition, fixed the ORC file generation of Orc_TPCHSuite.

[NSE-596] Add complex data types validation for ORC file format in gazelle 

---

native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarExpressionConverter.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarRegexp.scala

This patch implements regexp_replace
local unit tests

[NSE-581]impl regexp_replace

---

native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarDateTimeExpressions.scala

This patch fixes from_unixtime
closes: #576 
local unit tests

[NSE-576] fix from_unixtime

---

arrow-data-source/script/build_arrow.sh
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarBinaryExpression.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/JsonFunctionsSuite.scala

implement get_json_object
depends: https://github.com/oap-project/arrow/pull/49
local tests

[NSE-583] implement get_json_object

---

native-sql-engine/core/src/main/scala/com/intel/oap/expression/ConverterUtils.scala

This patch fixes sort w/ coalesce keys
pass jenkins

[NSE-604] fix sort w/ proj keys

---

native-sql-engine/core/src/main/scala/org/apache/spark/shuffle/ColumnarShuffleDependency.scala
native-sql-engine/core/src/main/scala/org/apache/spark/shuffle/ColumnarShuffleWriter.scala
native-sql-engine/core/src/main/scala/org/apache/spark/sql/execution/ColumnarShuffleExchangeExec.scala

[NSE-612] Add metric "prepare time" for shuffle writer

---

native-sql-engine/core/src/main/scala/com/intel/oap/expression/ConverterUtils.scala

[NSE-615] Add tackling for ColumnarEqualTo type in getResultAttrFromExpr of ConverterUtils

---

native-sql-engine/cpp/src/codegen/arrow_compute/ext/expression_codegen_visitor.cc
native-sql-engine/cpp/src/precompile/gandiva.h
native-sql-engine/cpp/src/tests/arrow_compute_test_precompile.cc

This patch implements get_json_object in codegen

[NSE-583] impl get_json_object in wscg

---

arrow-data-source/script/build_arrow.sh
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarBinaryExpression.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarDateTimeExpressions.scala

Subtract a date (DateType) from a given count (int32), result in DateType will be returned.

[NSE-609] Add support for date_sub expression

---

SECURITY.md

[NSE-627] Doc: adding security readme

---

native-sql-engine/core/src/main/java/com/intel/oap/vectorized/SchemaAwareArrowCompressedStreamReader.java
native-sql-engine/core/src/main/java/com/intel/oap/vectorized/SchemaAwareArrowStreamReader.java
native-sql-engine/core/src/main/java/com/intel/oap/vectorized/ShuffleSplitterJniWrapper.java
native-sql-engine/core/src/main/scala/com/intel/oap/GazellePluginConfig.scala
native-sql-engine/core/src/main/scala/com/intel/oap/vectorized/ArrowColumnarBatchSerializer.scala
native-sql-engine/core/src/main/scala/org/apache/spark/shuffle/ColumnarShuffleWriter.scala
native-sql-engine/core/src/main/scala/org/apache/spark/sql/execution/ColumnarShuffleExchangeExec.scala
native-sql-engine/core/src/test/scala/com/intel/oap/vectorized/ArrowColumnarBatchSerializerSuite.scala
native-sql-engine/cpp/src/jni/jni_wrapper.cc
native-sql-engine/cpp/src/shuffle/splitter.cc
native-sql-engine/cpp/src/shuffle/type.h

[NSE-631] Do not write schema in shuffle writting

---

arrow-data-source/common/pom.xml
arrow-data-source/parquet/pom.xml
arrow-data-source/pom.xml
arrow-data-source/standard/pom.xml
native-sql-engine/core/pom.xml
pom.xml
shims/common/pom.xml
shims/pom.xml
shims/spark311/pom.xml

version bump to 1.3.0-snapshot
N/A

[NSE-463] version bump to 1.3.0-SNAPSHOT

---

native-sql-engine/core/src/test/scala/com/intel/oap/vectorized/ArrowColumnarBatchSerializerSuite.scala

[NSE-650] Scala test ArrowColumnarBatchSerializerSuite is failing 

---

native-sql-engine/cpp/src/codegen/arrow_compute/ext/expression_codegen_visitor.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/whole_stage_codegen_kernel.cc

This patch removes extra headers/namespaces in codegen
pass jenkins

[NSE-126] remove extra headers/namespaces in codegen

---

native-sql-engine/cpp/src/jni/jni_wrapper.cc
native-sql-engine/cpp/src/shuffle/splitter.cc
native-sql-engine/cpp/src/shuffle/splitter.h
native-sql-engine/cpp/src/shuffle/type.h

[NSE-647] Leverage buffered write in shuffle 

---

native-sql-engine/core/src/main/scala/com/intel/oap/execution/ArrowRowToColumnarExec.scala

fix leakage in row to column operator
pass jenkins

[NSE-400] fix leakage in row to column operator

---

native-sql-engine/cpp/src/shuffle/splitter.cc

#684 
Require for arrow change https://github.com/oap-project/arrow/pull/75

[NSE-684] BufferedOutputStream causes massive futex system calls

---

.github/workflows/unittests.yml
native-sql-engine/core/src/test/scala/org/apache/spark/sql/execution/columnar/InMemoryColumnarQuerySuite.scala
native-sql-engine/cpp/src/operators/row_to_columnar_converter.cc
native-sql-engine/cpp/src/shuffle/splitter.cc
pom.xml

backport recent patches to 1.3 branch
pass Jenkins

[NSE-667] backport patches to 1.3 branch

---

native-sql-engine/cpp/src/codegen/arrow_compute/ext/conditioned_probe_kernel.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/hash_relation_kernel.cc

[NSE-610] hashjoin cleanup

---

native-sql-engine/cpp/src/benchmarks/arrow_compute_benchmark_join.cc

[NSE-692] JoinBenchmark is broken

---

README.md

fix some typo:
1. date_tpch_10 may be data_tpch_10
2. Could must be Cloud

Update README typo

---

README.md

Add Docker image and K8s usage in README
close #188 #372 
No need.

[NSE-188]Update Docker and K8s in README

---

README.md

Cherry-pick README Fix and Update.
Not necessary

backport README Update

---

CHANGELOG.md
docs/OAP-Developer-Guide.md
docs/OAP-Installation-Guide.md
docs/User-Guide.md

Update Changelog and OAP Documentation
N/A

[NSE-699] Update Changelog and OAP Documentation

---

arrow-data-source/common/pom.xml
arrow-data-source/parquet/pom.xml
arrow-data-source/pom.xml
arrow-data-source/standard/pom.xml
native-sql-engine/core/pom.xml
pom.xml
shims/common/pom.xml
shims/pom.xml
shims/spark311/pom.xml

[NSE-716][skip ci] version bump 1.4

---

native-sql-engine/cpp/src/codegen/common/relation_column.h

This patch fixes the null check in SMJ 
closes: #719

[NSE-719] fix null check in SMJ

---

native-sql-engine/cpp/src/codegen/common/relation_column.h

[NSE-719][backport]fix null check in SMJ

---

native-sql-engine/cpp/src/shuffle/splitter.cc
native-sql-engine/cpp/src/shuffle/splitter.h
native-sql-engine/cpp/src/tests/shuffle_split_test.cc

- Optimize Array split 
- Support nested Array
- Add nest UTs from customer side
- Fix previous largelist bug
- Add largelist UT

[NSE-712]  Optimize Array split and support nested Array

---

arrow-data-source/script/build_arrow.sh
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarUnaryOperator.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/DataFrameAggregateSuite.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/DataFrameSetOperationsSuite.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/DataFrameSuite.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/SQLQuerySuite.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/nativesql/NativeDataFrameAggregateSuite.scala

This patch depends on https://github.com/oap-project/arrow/pull/78.

[NSE-710] Add rand expression support

---

native-sql-engine/cpp/src/codegen/arrow_compute/ext/expression_codegen_visitor.cc

Fix codegen for out_of_range check
pass jenkins

[NSE-740] fix codegen with out_of_range check

---

native-sql-engine/core/src/main/scala/com/intel/oap/expression/ConverterUtils.scala

This patch fixes Q47 in TPC-DS
pass jenkins

[NSE-755] Quick fix for ConverterUtils.getAttrFromExpr for TPCDS queries

---

native-sql-engine/core/src/test/scala/com/intel/oap/misc/PartitioningSuite.scala

increase off-heap memory for SHJ tests
pass jenkins

[NSE-610] fix unit tests on SHJ

---

pom.xml

declare java.version for maven

[NSE-764] declare java.version for maven

---

.github/workflows/tpch.yml
.github/workflows/unittests.yml
arrow-data-source/README.md
arrow-data-source/common/pom.xml
arrow-data-source/parquet/pom.xml
arrow-data-source/pom.xml
arrow-data-source/script/build_arrow.sh
arrow-data-source/standard/pom.xml
docs/ApacheArrowInstallation.md
docs/Installation.md
native-sql-engine/core/pom.xml
native-sql-engine/cpp/src/CMakeLists.txt
pom.xml
shims/common/pom.xml
shims/pom.xml
shims/spark311/pom.xml
shims/spark321/pom.xml

[NSE-782] prepare 1.3.1 release

---

docs/Installation.md
docs/Prerequisite.md
docs/SparkInstallation.md
docs/User-Guide.md
docs/limitations.md
docs/memory.md
docs/performance.md

[NSE-761] Update document to reflect spark 3.2.x support

---

docs/Installation.md
docs/Prerequisite.md
docs/SparkInstallation.md
docs/User-Guide.md
docs/limitations.md
docs/memory.md
docs/performance.md

backport master changes to 1.3.1 branch
pass jenkins

[NSE-782] backport master changes to 1.3.1 branch 

---

CHANGELOG.md
TPP.txt
arrow-data-source/common/pom.xml
arrow-data-source/parquet/pom.xml
arrow-data-source/pom.xml
arrow-data-source/standard/pom.xml
docs/OAP-Developer-Guide.md
docs/OAP-Installation-Guide.md
docs/User-Guide.md
mkdocs.yml
native-sql-engine/core/pom.xml
pom.xml
shims/common/pom.xml
shims/pom.xml
shims/spark311/pom.xml
shims/spark321/pom.xml

Bump version and update documentation for OAP 1.3.1
N/A

[NSE-699] Bump version and update documentation for OAP 1.3.1

---

CHANGELOG.md
TPP.txt
docs/OAP-Developer-Guide.md
docs/OAP-Installation-Guide.md
docs/User-Guide.md
mkdocs.yml

Update documentation for OAP 1.3.1
N/A

[NSE-699] Update documentation for OAP 1.3.1

---

tools/gazelle_analysis.ipynb
tools/sparklog.ipynb

fix some bugs of script
add traceview info

fix bug of script

---

tools/gazelle_analysis.ipynb
tools/sparklog.ipynb

a little fix, use comments to show the traceview steps. NBconvert can't show in github

fix in eventlog script

---

native-sql-engine/core/src/main/scala/org/apache/spark/sql/execution/ColumnarCollapseCodegenStages.scala

This patch disabled SMJ with local limit as child
pass jenkins

[NSE-810] disable codegen for SMJ with local limit

---

arrow-data-source/standard/src/main/scala/com/intel/oap/spark/sql/ArrowWriteExtension.scala

As `ParquetFileFormat` extends from `ArrowFileFormat`, `ArrowWritePostRule` will add `ColumnarToFakeRowAdaptor` after Command. However `ParquetFileFormat` didn't support write with `FakeRow` and it will throw `java.lang.UnsupportedOperationException`.
This pr try to disable `ArrowWritePostRule` for `ParquetFileFormat` and add TODO to support ParquetFileFormat writing with arrow later.
unit test

[NSE-889] Failed to write with ParquetFileFormat while using ArrowWriteExtension

---

native-sql-engine/core/src/test/scala/com/intel/oap/misc/LimitSuite.scala

[NSE-909] fix slow test

---

native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarHashAggregateExec.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarHashAggregation.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/nativesql/NativeDataFrameAggregateSuite.scala
native-sql-engine/cpp/src/codegen/arrow_compute/ext/actions_impl.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/actions_impl.h
native-sql-engine/cpp/src/codegen/arrow_compute/ext/hash_aggregate_kernel.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/typed_action_codegen_impl.h
native-sql-engine/cpp/src/tests/arrow_compute_test_aggregate.cc

Support 'first' agg function.
UT & self-designed tests.

[NSE-869] Add 'first' agg function support

---

native-sql-engine/cpp/src/operators/columnar_to_row_converter_avx512.cc

[NSE-927] Extract and inline functions for native ColumnartoRow

---

tools/gazelle_analysis.ipynb
tools/sparklog.ipynb

add critical path breakdown
remove speculative killed stage

[DNM] update on sparklog script

---

native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarBinaryOperator.scala

This patch fixes the rlike wrong results
pass jenkins

[NSE-581] fix rlike/regexp_like results

---

native-sql-engine/core/src/main/java/com/intel/oap/vectorized/JniUtils.java

When spelculation is true, we meet the Exception of "faield to load libarrow.so" or "libarrow.so is too short", and we found tens of spark_columnar_plugin tmp dir was created in one executor.
unit tests.

[NSE-870] Failed to load arrow libraries while speculation is true

---

native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarWindowExec.scala
native-sql-engine/cpp/src/codegen/arrow_compute/expr_visitor.cc
native-sql-engine/cpp/src/codegen/arrow_compute/expr_visitor_impl.h
native-sql-engine/cpp/src/codegen/arrow_compute/ext/kernels_ext.h
native-sql-engine/cpp/src/codegen/arrow_compute/ext/window_kernel.cc

This patch implements the initial layout for row_number() in Window
pass jenkins

[NSE-862] implement row_number function

---

pom.xml

[NSE-913] Add support for Hadoop 3.3.1 when packaging

---

pom.xml

disable unit tests on spark32 package

[NSE-359] disable unit tests on spark32 package

---

native-sql-engine/cpp/src/CMakeLists.txt
native-sql-engine/cpp/src/codegen/arrow_compute/ext/codegen_common.cc
native-sql-engine/cpp/src/operators/columnar_to_row_converter.cc
native-sql-engine/cpp/src/shuffle/splitter.cc

[NSE-927][NSE-126] BackPort PR#975 and PR#977 to branch-1.4

---

arrow-data-source/standard/src/main/scala/com/intel/oap/spark/sql/execution/datasources/arrow/ArrowFileFormat.scala
arrow-data-source/standard/src/main/scala/com/intel/oap/spark/sql/execution/datasources/v2/arrow/ArrowPartitionReaderFactory.scala
arrow-data-source/standard/src/test/scala/com/intel/oap/spark/sql/execution/datasources/arrow/ArrowDataSourceTest.scala

[NSE-979] fix data source

---

native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarWindowExec.scala

[NSE-862] disable row_number() temporary

---

arrow-data-source/common/pom.xml
arrow-data-source/standard/pom.xml
docs/User-Guide.md
gazelle-dist/pom.xml
gazelle-dist/src/main/assembly/assembly.xml
native-sql-engine/core/pom.xml
pom.xml
shims/common/pom.xml
shims/spark311/pom.xml
shims/spark321/pom.xml

* Port from PR#825
* Generate two jars
* Use provided scope for scala and exclude meta-inf for jackson
* Add classifier
* Append spark version and pack to one jar
* Update user guide
* Revert "Add classifier"
This reverts commit f78d5dd949946a7b65cb40ae0b6c6e31d8781756.
* Refine the doc

[NSE-800] Pack the classes into one single jar

---

gazelle-dist/src/main/assembly/assembly.xml

[NSE-800] Fix an assembly warning (#1005)

---

.github/workflows/tpch.yml
.github/workflows/unittests.yml
CHANGELOG.md
TPP.txt
arrow-data-source/README.md
arrow-data-source/script/build_arrow.sh
docs/ApacheArrowInstallation.md
docs/Installation.md
docs/OAP-Developer-Guide.md
docs/OAP-Installation-Guide.md
docs/Prerequisite.md
docs/User-Guide.md
docs/index.md
mkdocs.yml

Update Changelog and documents for OAP 1.4.0
N/A

[NSE-699] Update Changelog and documents for OAP 1.4.0

---

native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarWindowExec.scala
native-sql-engine/cpp/src/codegen/arrow_compute/expr_visitor.cc
native-sql-engine/cpp/src/codegen/arrow_compute/expr_visitor_impl.h
native-sql-engine/cpp/src/codegen/arrow_compute/ext/window_kernel.cc

This patch improve row_number() to cover more cases
pass jenkins

[NSE-862] improve row_number()

---

arrow-data-source/script/build_arrow.sh
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarArithmetic.scala
native-sql-engine/tools/failed_ut_list.log

This patch depends on https://github.com/oap-project/arrow/pull/125. The change for arrow branch needs to be reverted at last.

[NSE-955] Support remainder function

---

arrow-data-source/script/build_arrow.sh
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarBinaryOperator.scala

Support a spark built-in function.
UT, self-designed test cases.

[NSE-955] Support find_in_set function

---

native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarDateTimeExpressions.scala

This patch fixes codegen check for unixtime related functions
pass jenkins

[NSE-1019] fix codegen for unixtimestamp

---

native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarExpressionConverter.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarTernaryOperator.scala

https://spark.apache.org/docs/3.2.1/api/sql/index.html#parse_url
unit tests

[NSE-955] Implement parse_url

---

arrow-data-source/common/src/main/scala/com/intel/oap/sql/execution/RowToArrowColumnarExec.scala

[NSE-958] Fix JVM R2C operator metrics

---

arrow-data-source/common/pom.xml
arrow-data-source/parquet/pom.xml
arrow-data-source/pom.xml
arrow-data-source/standard/pom.xml
gazelle-dist/pom.xml
native-sql-engine/core/pom.xml
pom.xml
shims/common/pom.xml
shims/pom.xml
shims/spark311/pom.xml
shims/spark321/pom.xml

version bump to 1.5

---

native-sql-engine/cpp/src/codegen/arrow_compute/ext/actions_impl.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/actions_impl.h

Only small improvements are brought.

[NSE-1071] Add tiny optimizations for hash aggregation functions

---

native-sql-engine/tools/failed_ut_list.log

The two UT failed from time to time. And they look not much related to gazelle.

Ignore two unit tests

---

native-sql-engine/core/src/test/scala/org/apache/spark/sql/nativesql/NativeSQLConvertedSuite.scala
native-sql-engine/cpp/src/codegen/arrow_compute/ext/actions_impl.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/hash_aggregate_kernel.cc

This patch fixes the hashagg w/ filter w/ groupby keys
new unit tests added

[NSE-1065] fix on count distinct w/ keys

---

native-sql-engine/core/src/main/scala/com/intel/oap/expression/ConverterUtils.scala
native-sql-engine/cpp/src/jni/jni_wrapper.cc

Fix memory leak for native C2R and R2C
pass jenkins

[NSE-400] Fix memory leak for native C2R and R2C.

---

native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarWindowExec.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarUnaryOperator.scala

[NSE-987] fix string date

---

native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarWindowExec.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarUnaryOperator.scala

This patch fixes the string date issue, backported from main branch
local tests

fix stringdate

---

native-sql-engine/cpp/src/shuffle/splitter.cc

remove debug log

---

native-sql-engine/core/src/main/java/com/intel/oap/vectorized/JniUtils.java

Use `FileUtils.forceDeleteOnExit` to remove tmp dir after application exits.
unit tests.

[NSE-1114] Remove tmp directory after application exits

---

native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarHashAggregateExec.scala
native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarSortMergeJoinExec.scala
native-sql-engine/core/src/main/scala/org/apache/spark/sql/execution/ColumnarCollapseCodegenStages.scala

This patch adds more checks for unsupported codegen patterns
pass jenkins

[NSE-1118] adding more checks for SMJ codegen

---

native-sql-engine/core/pom.xml

upgrade pgsql to 42.3.3
pass jenkins

[NSE-1149] upgrade pgsql to 42.3.3

---

shims/spark311/pom.xml
shims/spark32/pom.xml
shims/spark321/pom.xml
shims/spark322/pom.xml

upgrade guava to 24.1.1
pass jenkins

[NSE-1149] upgrade guava to 24.1.1

---

native-sql-engine/core/pom.xml

This patch upgrade junit to 4.13.1
pass jenkins

[NSE-1149] bump junit to 4.13.1

---

native-sql-engine/core/pom.xml

this patch upgrades pgsql to 42.3.7
pass jenkins

[NSE-1149] upgrade pgsql to 42.3.7

---

shims/spark32/pom.xml
shims/spark321/pom.xml
shims/spark322/pom.xml

this patch upgrades guava to 30.1.1
pass jenkins

[NSE-1149] upgrade guava to 30.1.1

---

CHANGELOG.md
docs/OAP-Developer-Guide.md
docs/OAP-Installation-Guide.md
docs/User-Guide.md
mkdocs.yml

Update Changelog and documents for OAP 1.5.0
N/A

[NSE-699] Update Changelog and documents for OAP 1.5.0

---

arrow-data-source/common/pom.xml
arrow-data-source/parquet/pom.xml
arrow-data-source/pom.xml
arrow-data-source/standard/pom.xml
gazelle-dist/pom.xml
native-sql-engine/core/pom.xml
pom.xml
shims/common/pom.xml
shims/pom.xml
shims/spark311/pom.xml
shims/spark32/pom.xml
shims/spark321/pom.xml
shims/spark322/pom.xml

prepare for 1.5 release
pass jenkins

[NSE-1189] prepare for 1.5.0 release
