oap-project/gazelle_plugin

core/src/main/java/com/intel/oap/vectorized/ExpressionEvaluator.java
core/src/main/scala/com/intel/oap/ColumnarGuardRule.scala
core/src/main/scala/org/apache/spark/sql/execution/ColumnarBroadcastExchangeExec.scala

[NSE-5][SCALA] Fix ColumnarBroadcastExchange didn't fallback issue w/ DPP

---

core/src/main/scala/com/intel/oap/execution/ColumnarSortMergeJoinExec.scala
core/src/main/scala/com/intel/oap/expression/ColumnarSortMergeJoin.scala
core/src/main/scala/org/apache/spark/sql/execution/ColumnarBroadcastExchangeExec.scala

[NSE-4]fix columnar BHJ on new memory pool

---

.gitmodules

[NSE-12]adding arrow-data-source as submodule

---

core/src/main/java/com/intel/oap/vectorized/ExpressionEvaluator.java
core/src/main/java/com/intel/oap/vectorized/ExpressionEvaluatorJniWrapper.java
core/src/main/scala/com/intel/oap/ColumnarPluginConfig.scala
cpp/src/codegen/arrow_compute/ext/array_item_index.h
cpp/src/codegen/arrow_compute/ext/basic_physical_kernels.cc
cpp/src/codegen/arrow_compute/ext/codegen_common.cc
cpp/src/codegen/arrow_compute/ext/codegen_common.h
cpp/src/codegen/arrow_compute/ext/codegen_context.h
cpp/src/codegen/arrow_compute/ext/conditioned_merge_join_kernel.cc
cpp/src/codegen/arrow_compute/ext/conditioned_probe_kernel.cc
cpp/src/codegen/arrow_compute/ext/expression_codegen_visitor.cc
cpp/src/codegen/arrow_compute/ext/expression_codegen_visitor.h
cpp/src/codegen/arrow_compute/ext/kernels_ext.h
cpp/src/codegen/arrow_compute/ext/whole_stage_codegen_kernel.cc
cpp/src/jni/jni_wrapper.cc

fixes: #17 
1.  postpone GetValue when value is required
2. Add a new config to enable/disable time breakdown metrics

[NSE-17] smjwscg optimization:

---

core/src/main/scala/com/intel/oap/execution/ColumnarBasicPhysicalOperators.scala
core/src/main/scala/com/intel/oap/execution/ColumnarBroadcastHashJoinExec.scala
core/src/main/scala/com/intel/oap/execution/ColumnarShuffledHashJoinExec.scala
core/src/main/scala/com/intel/oap/execution/ColumnarSortExec.scala
core/src/main/scala/com/intel/oap/execution/ColumnarSortMergeJoinExec.scala
core/src/main/scala/com/intel/oap/execution/ColumnarWholeStageCodegenExec.scala
core/src/main/scala/com/intel/oap/expression/ColumnarSorter.scala
core/src/main/scala/org/apache/spark/sql/execution/ColumnarCollapseCodegenStages.scala
cpp/src/codegen/arrow_compute/ext/conditioned_merge_join_kernel.cc
cpp/src/codegen/arrow_compute/ext/kernels_ext.cc

When DPP enabled, AQE won't work to replace smj with BHJ, so in Q95, there is one smj whose both sides are smj.
To fix this issue, 
1. we add a new strategy to split two wscg when smj are connected by build side.
2. we also added a support to treat any operator as buildSide operator in smj.
3. fix a bug when buildSide input is empty.
4. Add a strategy that If only one side child is smj, then this side will be treated as streamedSide
Fixed: https://github.com/oap-project/native-sql-engine/issues/22

[NSE-22]Fix w/DPP issue when inside wscg smj both sides are smj

---

core/src/main/scala/com/intel/oap/ColumnarGuardRule.scala
core/src/main/scala/com/intel/oap/ColumnarPlugin.scala
core/src/main/scala/com/intel/oap/execution/ColumnarBasicPhysicalOperators.scala
core/src/main/scala/com/intel/oap/execution/ColumnarBroadcastHashJoinExec.scala
core/src/main/scala/com/intel/oap/execution/ColumnarHashAggregateExec.scala
core/src/main/scala/com/intel/oap/execution/ColumnarShuffledHashJoinExec.scala
core/src/main/scala/com/intel/oap/execution/ColumnarSortExec.scala
core/src/main/scala/com/intel/oap/execution/DataToArrowColumnarExec.scala
core/src/main/scala/org/apache/spark/sql/execution/ColumnarBroadcastExchangeExec.scala
core/src/main/scala/org/apache/spark/sql/execution/ColumnarExchange.scala
core/src/main/scala/org/apache/spark/sql/execution/ColumnarShuffleExchangeExec.scala
core/src/main/scala/org/apache/spark/sql/execution/adaptive/ColumnarCustomShuffleReaderExec.scala
core/src/main/scala/org/apache/spark/sql/util/StructTypeFWD.scala

Fixed: https://github.com/oap-project/native-sql-engine/issues/27
verified with tpcds_v1_sf500_dpp and tpcds_v2_sf500

[NSE-27]Reuse exchage to optimize DPP performance

---

core/src/main/scala/com/intel/oap/execution/ColumnarSortExec.scala

This pr fixes driver failing to do sort codege, due to signature is empty.
The reason is filter not working for sortOrder containing projection exprs.
fixes https://github.com/oap-project/native-sql-engine/issues/40
under test

[NSE-40] fixes driver failing to do sort codege

---

core/src/main/scala/com/intel/oap/expression/ColumnarSorter.scala

partially fixes: #42 
this patch tries to close sort input when there's no next result in sort result iterator. In cases like columnar WSCG, this can help to release the memory on the first consumer operator of columnar sort, instead of waiting for the last operator to release all batches. 
verified locally

[NSE-42] early release sort input

---

core/src/main/scala/com/intel/oap/execution/ColumnarSortMergeJoinExec.scala
core/src/main/scala/com/intel/oap/expression/ColumnarSortMergeJoin.scala

[NSE-38]ColumnarSMJ: support expression as join keys

---

core/src/main/java/com/intel/oap/vectorized/SerializableObject.java
cpp/src/codegen/arrow_compute/ext/conditioned_merge_join_kernel.cc
cpp/src/codegen/arrow_compute/ext/conditioned_probe_kernel.cc
cpp/src/codegen/arrow_compute/ext/expression_codegen_visitor.cc
cpp/src/codegen/arrow_compute/ext/hash_relation_kernel.cc
cpp/src/codegen/common/hash_relation.h
cpp/src/codegen/common/relation_column.h
cpp/src/precompile/gandiva.h
cpp/src/tests/arrow_compute_test_wscg.cc
cpp/src/third_party/row_wise_memory/hashMap.h

couple optimization has been made:
1. if hash map key is unique, we will directly put its ArrayItemIndex in key map instead of link table,
2. hashmap size will be predicted by its total size, so small input will only allocate small size hash table
3. move hash calculation inside Get/IfExists function and add a cache their to fast fetch most recent probed key.
4. switch smj left and right sequence upon its numOutputFields.
5. skip is_null check in payload column
6. fix a small issue in round function
verified with TPCDS_DPP_SF500_V1 
Fixed: https://github.com/oap-project/native-sql-engine/issues/17

[NSE-17]TPCDS Q72 optimization

---

cpp/src/codegen/arrow_compute/ext/array_appender.h
cpp/src/codegen/arrow_compute/ext/conditioned_probe_kernel.cc
cpp/src/precompile/type_traits.h
cpp/src/tests/arrow_compute_test_join_wocg.cc

Fixed: https://github.com/oap-project/native-sql-engine/issues/53
This Issue is due to some join task in 24a/24b will expand input table 1000 times, which leads to output result contains 100 million + numRows, so the materialization is extremely slow
in this PR, we tried to accelerate materialization 
TODO:
If we can merge this Join with following Aggregate in a whole stage code gen, this issue may be fully fixed.

[NSE-53]Partial fix Q24a/Q24b tail SHJ task materialization performance issue

---

core/src/main/scala/com/intel/oap/expression/ColumnarSortMergeJoin.scala

This patch fixes columnar SMJ memory leakge
Fixes: #52 

[NSE-52]Columnar SMJ: fix memory leak by closing stream batches properly

---

core/src/main/scala/com/intel/oap/ColumnarGuardRule.scala

this patch introduce fallback on full outer join in columnar SMJ as it's not supported yet
related: #56 

[NSE-56]ColumnarSMJ: fallback on full outer join

---

core/src/main/scala/com/intel/oap/expression/ColumnarAggregation.scala
core/src/main/scala/com/intel/oap/expression/ColumnarSorter.scala

Fixed: https://github.com/oap-project/native-sql-engine/issues/58
Noticed that there is remains some queries with DPP enabled, some tasks' input will be totally empty, and this may leads to seg fault for ColumnarSort or ColumnarAggr, fix here

[NSE-58]Fix empty input issue when DPP enabled

---

core/src/main/scala/com/intel/oap/expression/ColumnarSorter.scala

This pr fixes the memleak in sort when SMJ is disabled, caused by batch close was not called by the consumer of sort operator (C2R).
fixes: https://github.com/oap-project/native-sql-engine/issues/64
verified on TPC-DS sf1000

[NSE-64] fix memleak in sort when SMJ is disabled

---

cpp/src/codegen/arrow_compute/ext/sort_kernel.cc

This pr removes the duplicate isNull check in codegen sort.
fixes: https://github.com/oap-project/native-sql-engine/issues/70
verified on TPC-DS sf1000.

[NSE-70] remove duplicate IsNull check in sort

---

cpp/src/codegen/arrow_compute/ext/conditioned_merge_join_kernel.cc
cpp/src/codegen/arrow_compute/ext/merge_join_kernel.cc

This patch improves SMJ to use `std::forward_as_tuple ` instead of `std::make_tuple` which can save one memory copy when constructing tuple
partially fixes: #73 

[NSE-73]using data ref in multiple keys based SMJ

---

.github/workflows/report_ram_log.yml
.github/workflows/tpch.yml
core/src/main/java/com/intel/oap/vectorized/ArrowWritableColumnVector.java
core/src/main/java/com/intel/oap/vectorized/BatchIterator.java
core/src/main/java/com/intel/oap/vectorized/SerializableObject.java
core/src/main/scala/com/intel/oap/ColumnarPluginConfig.scala
core/src/main/scala/com/intel/oap/execution/BroadcastColumnarRDD.scala
core/src/main/scala/com/intel/oap/execution/ColumnarBroadcastHashJoinExec.scala
core/src/main/scala/com/intel/oap/execution/ColumnarShuffledHashJoinExec.scala
core/src/main/scala/com/intel/oap/execution/ColumnarWholeStageCodegenExec.scala
core/src/main/scala/com/intel/oap/expression/ConverterUtils.scala
core/src/main/scala/org/apache/spark/sql/execution/ColumnarBroadcastExchangeExec.scala
core/src/main/scala/org/apache/spark/sql/execution/ColumnarHashedRelation.scala
core/src/test/java/com/intel/oap/tpch/MallocUtils.java
core/src/test/scala/com/intel/oap/tpch/MemoryUsageTest.scala
cpp/src/codegen/common/hash_relation.h
cpp/src/jni/jni_wrapper.cc
cpp/src/third_party/row_wise_memory/hashMap.h

#45 
This is ideally to fix leaks and reduce process RSS during BHJ-related query execution. Still doing a final check for memory segmentation and other minor stuffs.
Checklist:
1. BHJ: Fix unclosed hash map on driver
2. BHJ: Fix unclosed input batches on driver
3. Remove use of unreliable  JVM API `finalize()`
4. Remove ref-count for java-side hash maps (we should avoid creating more manual ref-count logic in JVM code unless performance getting really worse)
5. Remove option `broadcastCacheTimeout` which is no longer needed.

[NSE-45] BHJ memory leak

---

cpp/src/tests/arrow_compute_test_aggregate.cc
cpp/src/tests/arrow_compute_test_hashaggregate.cc
cpp/src/tests/arrow_compute_test_join.cc
cpp/src/tests/arrow_compute_test_join_smj.cc
cpp/src/tests/arrow_compute_test_sort.cc

This patch fixes c++ unit tests building 

[NSE-48] fix c++ unit tests

---

core/src/main/scala/com/intel/oap/execution/ColumnarBasicPhysicalOperators.scala
core/src/main/scala/com/intel/oap/execution/ColumnarHashAggregateExec.scala
core/src/main/scala/com/intel/oap/expression/ColumnarArithmetic.scala
core/src/main/scala/com/intel/oap/expression/ColumnarBinaryOperator.scala
core/src/main/scala/com/intel/oap/expression/ColumnarCaseWhenOperator.scala
core/src/main/scala/com/intel/oap/expression/ColumnarCoalesceOperator.scala
core/src/main/scala/com/intel/oap/expression/ColumnarConcatOperator.scala
core/src/main/scala/com/intel/oap/expression/ColumnarIfOperator.scala
core/src/main/scala/com/intel/oap/expression/ColumnarLiterals.scala
core/src/main/scala/com/intel/oap/expression/ColumnarTernaryOperator.scala
core/src/main/scala/com/intel/oap/expression/ColumnarUnaryOperator.scala

This pr added more datatype fallback logic in columnar operators.
With this pr, the official TPC-DS works on double dataset. 
https://github.com/oap-project/native-sql-engine/issues/51
locally tested

[NSE-51] add more datatype fallback logic in columnar operators

---

cpp/src/codegen/arrow_compute/ext/conditioned_probe_kernel.cc

Noticed that there may be null probe key when doing hash join, fix in this PR

[NSE-82] Fix Q72 SF1536 incorrect result

---

core/src/main/java/com/intel/oap/vectorized/ArrowWritableColumnVector.java

fixes: #81 
Miss some setNulls implementation in ArrowWritableCV

[NSE-81] add missing setNulls methods in ArrowWritableColumnVector

---

core/src/main/scala/com/intel/oap/execution/ColumnarWholeStageCodegenExec.scala
cpp/src/codegen/arrow_compute/ext/expression_codegen_visitor.cc

Fixed: https://github.com/oap-project/native-sql-engine/issues/100

[NSE-100]Fix an incorrect result error when using SHJ in Q45

---

cpp/src/codegen/arrow_compute/ext/code_generator_base.h
cpp/src/codegen/arrow_compute/ext/sort_kernel.cc

In this pr, we reduced the codegen in multiple-key sort.
fixes: https://github.com/oap-project/native-sql-engine/issues/103
locally tested, the codegen times decrease from 55 to 18.

[NSE-103] reduce codegen in multiple-key sort

---

cpp/src/codegen/arrow_compute/ext/sort_kernel.cc

This pr optimized the null check in codegen sort.
fixes https://github.com/oap-project/native-sql-engine/issues/97
locally tested

[NSE-97] remove isnull when null count is zero

---

core/src/main/java/com/intel/oap/vectorized/ArrowCompressedStreamReader.java
core/src/main/java/com/intel/oap/vectorized/ShuffleSplitterJniWrapper.java
core/src/main/scala/com/intel/oap/ColumnarPluginConfig.scala
core/src/main/scala/com/intel/oap/expression/ConverterUtils.scala
core/src/main/scala/com/intel/oap/vectorized/ArrowColumnarBatchSerializer.scala
core/src/main/scala/org/apache/spark/shuffle/ColumnarShuffleWriter.scala
cpp/src/jni/jni_wrapper.cc
cpp/src/shuffle/splitter.cc
cpp/src/shuffle/splitter.h

This pr is to support adaptive compression select in Shuffle.
Fix [PR#68](https://github.com/oap-project/native-sql-engine/issues/68)
Existing unit test and TPCH benchmark locally

[NSE-68][Shuffle] Adaptive compression select in Shuffle.

---

cpp/src/codegen/arrow_compute/ext/array_appender.h
cpp/src/codegen/arrow_compute/ext/sort_kernel.cc

This pr 
- optimized the null check
- refactored the sort kernels
- used reference in cmp function
fixes https://github.com/oap-project/native-sql-engine/issues/97
locally tested

[NSE-97] optimize null check and refactor sort kernels

---

core/src/main/scala/com/intel/oap/ColumnarPlugin.scala
core/src/test/scala/com/intel/oap/tpc/TableGen.scala
core/src/test/scala/com/intel/oap/tpc/ds/TPCDSSuite.scala
core/src/test/scala/com/intel/oap/tpc/ds/TPCDSTableGen.scala
core/src/test/scala/com/intel/oap/tpc/h/TPCHSuite.scala
core/src/test/scala/com/intel/oap/tpc/h/TPCHTableGen.scala
cpp/src/codegen/arrow_compute/expr_visitor_impl.h
cpp/src/codegen/arrow_compute/ext/kernels_ext.h
cpp/src/codegen/arrow_compute/ext/window_kernel.cc
cpp/src/codegen/arrow_compute/ext/window_sort_kernel.h

In TPC-DS this is typically for query 67 to improve the huge RANK window.

[NSE-120] Columnar window: Reduce peak memory usage and fix performance issues

---

core/src/main/scala/com/intel/oap/execution/ColumnarDataSourceRDD.scala
core/src/main/scala/org/apache/spark/sql/util/OASPackageBridge.scala

fixes: #134 
This is to add input size to stage metrics shown on UI when using columnar plugin.
Only available in DataSourceV2.

[NSE-134] Update input metrics during reading

---

core/src/main/scala/com/intel/oap/execution/ColumnarBasicPhysicalOperators.scala
core/src/main/scala/com/intel/oap/expression/ColumnarArithmetic.scala
core/src/main/scala/com/intel/oap/expression/ColumnarBinaryOperator.scala
core/src/main/scala/com/intel/oap/expression/ColumnarBoundAttribute.scala
core/src/main/scala/com/intel/oap/expression/ColumnarCaseWhenOperator.scala
core/src/main/scala/com/intel/oap/expression/ColumnarCoalesceOperator.scala
core/src/main/scala/com/intel/oap/expression/ColumnarIfOperator.scala
core/src/main/scala/com/intel/oap/expression/ColumnarUnaryOperator.scala
cpp/src/CMakeLists.txt
cpp/src/codegen/arrow_compute/ext/expression_codegen_visitor.cc
cpp/src/precompile/array.h
cpp/src/precompile/gandiva.h
cpp/src/tests/arrow_compute_test_precompile.cc
cpp/src/third_party/gandiva/CMakeLists.txt
cpp/src/third_party/gandiva/decimal_ops.cc
cpp/src/third_party/gandiva/decimal_ops.h

fixes: https://github.com/oap-project/native-sql-engine/issues/130

[NSE-130] support decimal in project

---

core/src/main/scala/com/intel/oap/execution/ColumnarSortMergeJoinExec.scala
core/src/main/scala/com/intel/oap/expression/ColumnarSortMergeJoin.scala
cpp/src/codegen/arrow_compute/ext/codegen_node_visitor.cc
cpp/src/codegen/arrow_compute/ext/codegen_node_visitor.h
cpp/src/codegen/arrow_compute/ext/merge_join_kernel.cc
cpp/src/codegen/common/relation.cc
cpp/src/codegen/common/relation_column.h

this patches adds decimal support for SMJ
related: #31

[NSE-31]decimal support for SMJ

---

core/src/main/scala/com/intel/oap/expression/ColumnarUnaryOperator.scala
cpp/src/codegen/arrow_compute/ext/actions_impl.cc
cpp/src/codegen/arrow_compute/ext/expression_codegen_visitor.cc
cpp/src/codegen/common/hash_relation.h
cpp/src/precompile/gandiva.h
cpp/src/tests/arrow_compute_test_precompile.cc
cpp/src/third_party/row_wise_memory/hashMap.h

For now, q32, q32, q39a, q54 should be fixed.
Q65 and Q69 may need to verify on partition dataset

[NSE-153] Fix incorrect quries after enabled Decimal

---

native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarArithmetic.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarUnaryOperator.scala
native-sql-engine/cpp/src/codegen/arrow_compute/ext/expression_codegen_visitor.cc
native-sql-engine/cpp/src/precompile/gandiva.h
native-sql-engine/cpp/src/tests/arrow_compute_test_precompile.cc

This pr fixes overflow and precision loss in projection.
https://github.com/oap-project/native-sql-engine/issues/130
under test

[NSE-130] fix overflow and precision loss

---

native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarArithmetic.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarExpressionConverter.scala

This pr fixes precision loss in divide by using resType from CheckOverflow.
https://github.com/oap-project/native-sql-engine/issues/130
locally tested

[NSE-130] fix precision loss in divide w/ decimal type

---

native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarArithmetic.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarRoundOperator.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarUnaryOperator.scala
native-sql-engine/cpp/src/codegen/arrow_compute/ext/expression_codegen_visitor.cc
native-sql-engine/cpp/src/precompile/gandiva.h
native-sql-engine/cpp/src/tests/arrow_compute_test_precompile.cc

We noticed decimal abs/round would fallback, so in this pr, decimal round and abs are supported.
https://github.com/oap-project/native-sql-engine/issues/130
verified on TPC-DS

[NSE-130] support decimal round and abs

---

native-sql-engine/cpp/src/codegen/arrow_compute/ext/expression_codegen_visitor.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/sort_kernel.cc
native-sql-engine/cpp/src/precompile/builder.cc
native-sql-engine/cpp/src/precompile/builder.h
native-sql-engine/cpp/src/precompile/gandiva.h

This patch switch back to use the old logic, which seems faster on my env
```
for each column
for each index
builder append
```
partially reverts: 
https://github.com/oap-project/native-sql-engine/pull/104/commits/24d8b681897fc489eb3ab18eb89d08fe20ff076e

[NSE-170]improve sort shuffle code

---

native-sql-engine/cpp/src/codegen/arrow_compute/ext/sort_kernel.cc

This pr fixes the incorrect result of q69, occurring due to wrong offset and size when copying bitmap.
fixed https://github.com/oap-project/native-sql-engine/issues/173.
https://github.com/oap-project/native-sql-engine/issues/153
q69 was verified, other queries are under testing

[NSE-173] fix incorrect result of q69

---

native-sql-engine/core/src/main/java/com/intel/oap/vectorized/JniUtils.java
native-sql-engine/cpp/src/CMakeLists.txt

Close #191 
Tested on my developing server(Shared Case and Existing Case) and a new server without arrow installed(Shared Case)

[NSE-191]Fix issue0191 for .so file copy to tmp.

---

native-sql-engine/cpp/src/codegen/arrow_compute/ext/hash_relation_kernel.cc
native-sql-engine/cpp/src/codegen/common/hash_relation.h

This issue is caused by when numKeys to build hashmap is too big, it will overflow hashmap size.
So we now will use IntMax to bound hashmap size.
According to test, q14a should be able to finish, while it will take extremely long to build hashMap
Fixed: https://github.com/oap-project/native-sql-engine/issues/167

[NSE-167]Fix q14a/b segfault

---

native-sql-engine/cpp/src/CMakeLists.txt

Close #194 
This PR has been tested on my developing server and pass the testing for all TPC-DS 99 queries.

[NSE-194]Turn on several Arrow parameters

---

native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarConditionProjector.scala

This is to fix inefficient columnar project executions brought by PR #151 . Other queries that result in field projections may also be accelerated (untested).

[NSE-185] Avoid unnecessary copying when simply projecting on fields

---

native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarShuffledHashJoinExec.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarConditionedProbeJoin.scala
native-sql-engine/cpp/src/codegen/arrow_compute/ext/hash_relation_kernel.cc
native-sql-engine/cpp/src/codegen/common/hash_relation.h
native-sql-engine/cpp/src/third_party/row_wise_memory/hashMap.h

Continuously optimize q14a and q14b to accelerate hash map build
optimized: https://github.com/oap-project/native-sql-engine/issues/167

[NSE-167]Hashmap build opt for semi/anti/exists join

---

native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarUnaryOperator.scala

This PR add the month() and dayofmonth() support in native sql engine. Fix [#198](https://github.com/oap-project/native-sql-engine/issues/198)
pass the test in  DateFunctionsSuite# test("month") and test("dayofmonth")

[NSE-198] support the month() and dayofmonth() functions with DateType

---

native-sql-engine/cpp/src/codegen/arrow_compute/ext/array_appender.h
native-sql-engine/cpp/src/codegen/arrow_compute/ext/sort_kernel.cc

This patch adds an unsafe appender which will reserve space before builder array. 
The boolean builder is not touched as only malloc small sized memory
The string builder are not touched as it's diffcult to pre-allocate the space
On my 2node env this can improve TPC-DS performance by ~5%
This approach is applied to Sort operator only. 
related: #170 

[NSE-170] using unsafe appender

---

native-sql-engine/cpp/src/codegen/arrow_compute/ext/codegen_node_visitor.cc

fix missing castDECIMAL in SMJ codegen
note this is a quick fix, all SMJ code will be moved to use new APIs.
fixes: #217 

[NSE-217] fix missing decimal check

---

native-sql-engine/cpp/src/codegen/arrow_compute/ext/hash_aggregate_kernel.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/whole_stage_codegen_kernel.cc

This patch fixes hashagg and wscg to use correct batch size 
fixes: #119 

[NSE-119]allow to config batchsize in hashagg and wscg

---

native-sql-engine/core/src/main/java/com/intel/oap/datasource/parquet/ParquetReader.java
native-sql-engine/core/src/main/java/com/intel/oap/vectorized/JniUtils.java
native-sql-engine/cpp/src/codegen/arrow_compute/code_generator.h
native-sql-engine/cpp/src/codegen/arrow_compute/ext/basic_physical_kernels.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/codegen_common.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/codegen_node_visitor.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/conditioned_merge_join_kernel.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/conditioned_probe_kernel.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/expression_codegen_visitor.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/hash_aggregate_kernel.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/hash_relation_kernel.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/kernels_ext.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/kernels_ext.h
native-sql-engine/cpp/src/codegen/arrow_compute/ext/merge_join_kernel.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/probe_kernel.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/sort_kernel.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/whole_stage_codegen_kernel.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/window_kernel.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/window_sort_kernel.h
native-sql-engine/cpp/src/codegen/expr_visitor.h
native-sql-engine/cpp/src/jni/jni_wrapper.cc
native-sql-engine/cpp/src/precompile/array.cc
native-sql-engine/cpp/src/precompile/gandiva.h
native-sql-engine/cpp/src/precompile/hash_arrays_kernel.cc
native-sql-engine/cpp/src/shuffle/splitter.cc

fix vulnerabilities from code scan

[NSE-227]fix issues from codescan

---

native-sql-engine/cpp/src/tests/shuffle_split_test.cc

Fix [#229](https://github.com/oap-project/native-sql-engine/issues/229)

[NSE-229] Fix the deprecated code warning in shuffle_split_test

---

native-sql-engine/cpp/src/precompile/gandiva.h

[NSE-239] Adopt ARROW-7011

---

native-sql-engine/core/src/main/scala/com/intel/oap/ColumnarGuardRule.scala
native-sql-engine/core/src/main/scala/com/intel/oap/ColumnarPluginConfig.scala

[NSE-196] clean up native sql options

---

.github/workflows/tpch.yml
native-sql-engine/core/src/test/scala/com/intel/oap/tpc/ds/TPCDSSuite.scala
native-sql-engine/core/src/test/scala/com/intel/oap/tpc/h/TPCHSuite.scala

This patch disable the long ram report for each pr, instead we trigger this by adding "RAM report" label
github action

[NSE-256] do not run ram report test on each PR

---

arrow-data-source/pom.xml
arrow-data-source/standard/src/main/scala/com/intel/oap/spark/sql/execution/datasources/v2/arrow/ArrowUtils.scala
arrow-data-source/standard/src/test/scala/com/intel/oap/spark/sql/execution/datasources/arrow/ArrowDataSourceTest.scala
native-sql-engine/core/pom.xml

[NSE-261] ArrowDataSource: Add S3 Support

---

native-sql-engine/cpp/src/codegen/arrow_compute/ext/hash_aggregate_kernel.cc
native-sql-engine/cpp/src/shuffle/splitter.cc

Related to [#265 ](https://github.com/oap-project/native-sql-engine/issues/265)
fixes: #241 
shuffle builder use UnsafeAppend API for better performance. it
tries to reserve enough space based on results of last recordbatch,
this maybe not buggy if there's a dense recordbatch after a sparse one.
this patch adds below fixes:
- adds Reset() after Finish() in builder
- reserve length for offset_builder in binary builder
A further clean up on the reservation logic should be needed.

[NSE-265] Reserve enough memory before UnsafeAppend in builder

---

native-sql-engine/cpp/src/codegen/arrow_compute/ext/hash_aggregate_kernel.cc

[NSE-119] clean up on comments

---

README.md
docs/Configuration.md
docs/Installation.md

Close #206 Close #287 
Document Update Only.

[NSE-206]Update installation guide and configuration guide.

---

native-sql-engine/core/src/main/scala/com/intel/oap/ColumnarGuardRule.scala
native-sql-engine/core/src/main/scala/com/intel/oap/ColumnarPlugin.scala
native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarInMemoryRelation.scala
native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarInMemoryTableScanExec.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarConditionProjector.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ConverterUtils.scala
native-sql-engine/core/src/main/scala/org/apache/spark/sql/columnar/CachedBatchSerializer.scala
native-sql-engine/core/src/main/scala/org/apache/spark/sql/execution/columnar/InMemoryRelation.scala

Fixed: https://github.com/oap-project/native-sql-engine/issues/245

[NSE-245]Adding columnar RDD cache support

---

native-sql-engine/cpp/src/codegen/common/hash_relation.h

fixes: #293 
locally verified on TPCH-Q9

[NSE-293] fix unsafemap with key = '0'

---

arrow-data-source/pom.xml
native-sql-engine/core/pom.xml

This pr fixes the multiple bindings of slf4j.
fixed: https://github.com/oap-project/native-sql-engine/issues/257
locally tested

[NSE-257] fix multiple slf4j bindings

---

arrow-data-source/pom.xml
native-sql-engine/core/pom.xml
native-sql-engine/core/src/main/scala/com/intel/oap/ColumnarGuardRule.scala
native-sql-engine/core/src/main/scala/com/intel/oap/ColumnarPlugin.scala
native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarWindowExec.scala
native-sql-engine/core/src/test/scala/com/intel/oap/tpc/ds/TPCDSSuite.scala
native-sql-engine/cpp/src/codegen/arrow_compute/ext/actions_impl.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/kernels_ext.h
native-sql-engine/cpp/src/codegen/arrow_compute/ext/window_kernel.cc
pom.xml

[NSE-285] ColumnarWindow: Support Date input in MAX/MIN

---

native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarBroadcastHashJoinExec.scala
native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarShuffledHashJoinExec.scala

This pr fixed the out partitioning issue in BHJ and SHJ.
fixed https://github.com/oap-project/native-sql-engine/issues/329.
verified on v2/v1

[NSE-329] fix out partitioning in BHJ and SHJ

---

native-sql-engine/core/pom.xml

the new release of scala-maven-plugin(4.5.x) seems buggy on incremental
compile, using 4.4.0 instead
fixes: #325 

[NSE-325] fix incremental compile issue with 4.5.x scala-maven-plugin

---

README.md

made small modification of Readme introduction for better user experience.
N/A

[NSE-330]Refine Readme introduction

---

native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarHashAggregateExec.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarHashAggregation.scala
native-sql-engine/cpp/src/codegen/arrow_compute/ext/actions_impl.cc
native-sql-engine/cpp/src/tests/arrow_compute_test_aggregate.cc
native-sql-engine/cpp/src/tests/arrow_compute_test_wscg.cc

This pr fixed the unsuppored types in aggregate.
https://github.com/oap-project/native-sql-engine/issues/207
verified on TPC-DS v2, TPC-DS v1

[NSE-207] fix unsuppored types in aggregate

---

pom.xml

This pr fixed the build failure on v2 with -Phadoop-3.2
fixed: https://github.com/oap-project/native-sql-engine/issues/341
locally tested

[NSE-341] fix maven build failure

---

native-sql-engine/cpp/src/codegen/arrow_compute/ext/codegen_common.cc

this patch allows to config codegen opt level. 
fixes: #343 

[NSE-343]allow to config codegen opt level

---

.github/workflows/unittests.yml
native-sql-engine/core/pom.xml

fixed: https://github.com/oap-project/native-sql-engine/issues/360
locally tested

[NSE-360] fix ut compile and travis test

---

docs/Configuration.md
pom.xml

This patch makes arrow-unsafe allocator as default profile
arrow-netty will instance netty memory pool to reduce the
alloc/dealloc overhead which introduced big memory footprint.
local perf tests showed the performace is not heavily impacted
after switch to arrow-unsafe
one more benefit is we could remove the -XX:MaxDirectMemorySize flag
which also impacts the vanilla Spark memory usage
fixes #362 

[NSE-362] use arrow-unsafe allocator by default

---

native-sql-engine/cpp/src/codegen/arrow_compute/ext/whole_stage_codegen_kernel.cc
native-sql-engine/cpp/src/precompile/unsafe_array.cc

Fix timestamp in native side.
https://github.com/oap-project/native-sql-engine/issues/183
under test

[NSE-183] fix timestamp in native side

---

arrow-data-source/pom.xml
native-sql-engine/core/pom.xml
pom.xml

1. Add hadoop.version for hadoop client in arrow-data-source and native-sql-engine
2. Add profile setting for hadoop version control, default use hadoop 2.7.4
3. Fixing one issue for the variable: hadoop.version does not apply to hadoop-client library in compiler phase before.
4. Move the order of profile section to higher for better reading
Tested in local server.

[NSE-382]Fix Hadoop version issue

---

pom.xml

Add Hadoop 3.2.2 for GCP Dataproc 2.0 support
Close #382 
The jar has been tested on GCP Dataproc 2.0 image and pass all TPC-DS queries in SF2.

[NSE-382]Support GCP Dataproc 2.0

---

native-sql-engine/core/src/main/scala/com/intel/oap/ColumnarGuardRule.scala
native-sql-engine/core/src/main/scala/com/intel/oap/ColumnarPlugin.scala
native-sql-engine/core/src/main/scala/com/intel/oap/ColumnarPluginConfig.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarProjection.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ConverterUtils.scala
native-sql-engine/core/src/main/scala/org/apache/spark/sql/execution/python/ColumnarArrowEvalPythonExec.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/execution/python/ArrowEvalPythonExecSuite.scala

Main functionality is working, UT is added, jupyter script as below
```
import findspark
findspark.init()
import os
from pyspark.sql import *
from pyspark import *
import pyspark.sql.functions as F
from pyspark.sql.types import *
native_sql_path = "/mnt/nvme2/chendi/intel-bigdata/OAP/native-sql-engine/native-sql-engine/core/target/spark-columnar-core-1.2.0-snapshot-jar-with-dependencies.jar"
native_arrow_datasource_path = "/mnt/nvme2/chendi/intel-bigdata/OAP/native-sql-engine/arrow-data-source/standard/target/spark-arrow-datasource-standard-1.2.0-snapshot-jar-with-dependencies.jar"
spark = SparkSession.builder.master('yarn')\
.appName("udf_test")\
.config("spark.executorEnv.LD_LIBRARY_PATH", "/usr/local/lib64/")\
.config("spark.driver.extraClassPath", …
```

[NSE-394]Support ColumnarArrowEvalPython operator

---

pom.xml

Add AWS EMR 6.3.0 Support with Hadoop 3.2.1.
Close #368 
The jar has been tested in AWS EMR 6.3.0 and can pass all 99 TPC-DS queries(turn off adaptive).

[NSE-368]Update emr-6.3.0 support

---

.github/workflows/unittests.yml
native-sql-engine/core/src/main/java/com/intel/oap/vectorized/ArrowColumnarToRowJniWrapper.java
native-sql-engine/core/src/main/scala/com/intel/oap/ColumnarPlugin.scala
native-sql-engine/core/src/main/scala/com/intel/oap/ColumnarPluginConfig.scala
native-sql-engine/core/src/main/scala/com/intel/oap/execution/ArrowColumnarToRowExec.scala
native-sql-engine/cpp/src/CMakeLists.txt
native-sql-engine/cpp/src/jni/jni_wrapper.cc
native-sql-engine/cpp/src/operators/unsafe_row_writer_and_reader.cc
native-sql-engine/cpp/src/operators/unsafe_row_writer_and_reader.h
native-sql-engine/cpp/src/tests/CMakeLists.txt
native-sql-engine/cpp/src/tests/test_utils.h
native-sql-engine/cpp/src/tests/unsaferow_test.cc

This PR replace the ColumnarToRow operator with the ArrowColumnarToRow operator, which convert the RDD[ColumnBatch] to Arrow RecordBatch and then convert the Arrow Record Batch to Spark UnsafeRow.
UT added
locally verified on TPC-DS

[NSE-400] Optimize ColumnarToRow Operator in NSE.

---

native-sql-engine/core/src/main/java/com/intel/oap/vectorized/ExpressionEvaluator.java
native-sql-engine/core/src/main/java/com/intel/oap/vectorized/ExpressionEvaluatorJniWrapper.java
native-sql-engine/core/src/main/scala/com/intel/oap/ColumnarPlugin.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarSorter.scala
native-sql-engine/cpp/compile.sh
native-sql-engine/cpp/src/codegen/arrow_compute/code_generator.h
native-sql-engine/cpp/src/codegen/arrow_compute/expr_visitor.cc
native-sql-engine/cpp/src/codegen/arrow_compute/expr_visitor.h
native-sql-engine/cpp/src/codegen/arrow_compute/expr_visitor_impl.h
native-sql-engine/cpp/src/codegen/arrow_compute/ext/array_appender.h
native-sql-engine/cpp/src/codegen/arrow_compute/ext/code_generator_base.h
native-sql-engine/cpp/src/codegen/arrow_compute/ext/hash_relation_kernel.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/kernels_ext.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/kernels_ext.h
native-sql-engine/cpp/src/codegen/arrow_compute/ext/merge_join_kernel.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/sort_kernel.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/window_kernel.cc
native-sql-engine/cpp/src/codegen/code_generator.h
native-sql-engine/cpp/src/codegen/compute_ext/code_generator.h
native-sql-engine/cpp/src/codegen/gandiva/code_generator.h
native-sql-engine/cpp/src/jni/jni_wrapper.cc
native-sql-engine/cpp/src/tests/arrow_compute_test_join_wocg.cc
native-sql-engine/cpp/src/tests/arrow_compute_test_sort.cc

This patch add spill support for sort. 
- The Spill() API of Sort is connected to the TaskMemoryManager of Spark. If under lower memory, Spark will try toissue Spill on Sort. 
- On Spill() is called, executor will try to pick one partiton(one task) then try to write the sort content(keys + payloads) to disks, then release the memory for these consents. For following outputing, sort will first load the spill contents into memory then continue to output the results.
- Please note the Spill will be only called from the following operators of Sort, like SortMergeJoin - this makes spill happens only on sort results outputting phase.
- Currently the spill files will be written into each yarn container, this should be improved to use Spark's blockmanager.

[NSE-417] Sort spill support framework

---

native-sql-engine/core/src/main/scala/com/intel/oap/execution/ArrowColumnarToRowExec.scala

This PR disable the wholestagecodegen feature in ArrowColumnarToRow operator and will enable later.
[#421 ](https://github.com/oap-project/gazelle_plugin/issues/421)

[NSE-421]Disable the wholestagecodegen feature for the ArrowColumnarToRow operator

---

native-sql-engine/cpp/src/codegen/arrow_compute/expr_visitor_impl.h
native-sql-engine/cpp/src/codegen/arrow_compute/ext/sort_kernel.cc
native-sql-engine/cpp/src/tests/arrow_compute_test_sort.cc

this patch fix spill on inplace sort, which is not supported yet
also cleaned up on the debug logs.

[NSE-417] fix sort spill on inplsace sort

---

pom.xml

Return maven assemble plugin to 3.0.0 since there is a potential fail when using build from source.
Tested in local server

[NSE-254]Issue0410 jar size

---

arrow-data-source/standard/pom.xml
arrow-data-source/standard/src/test/scala/com/intel/oap/spark/sql/execution/datasources/arrow/ArrowDataSourceTest.scala
native-sql-engine/core/pom.xml
native-sql-engine/core/src/main/scala/com/intel/oap/ColumnarPluginConfig.scala
native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarHashAggregateExec.scala
native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarWindowExec.scala
native-sql-engine/core/src/test/scala/com/intel/oap/misc/DateTimeSuite.scala
native-sql-engine/core/src/test/scala/com/intel/oap/tpc/ds/TPCDSSuite.scala
native-sql-engine/core/src/test/scala/com/intel/oap/vectorized/ArrowColumnarBatchSerializerSuite.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/DataFrameAggregateSuite.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/DataFrameWindowFunctionsSuite.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/DateFunctionsSuite.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/PlanStabilitySuite.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/RepartitionSuite.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/nativesql/NativeDataFrameAggregateSuite.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/nativesql/NativeRepartitionSuite.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/nativesql/NativeSQLConvertedSuite.scala
native-sql-engine/cpp/src/codegen/arrow_compute/ext/hash_aggregate_kernel.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/typed_action_codegen_impl.h
native-sql-engine/cpp/src/codegen/common/relation_column.h
native-sql-engine/cpp/src/codegen/common/sort_relation.h
native-sql-engine/tools/failed_ut_list.log
native-sql-engine/tools/run_ut.sh
pom.xml

backport master patches to 1.2 branch

[NSE-451] backport patches to 1.2

---

native-sql-engine/core/src/main/java/com/intel/oap/vectorized/JniUtils.java
native-sql-engine/cpp/src/CMakeLists.txt
pom.xml

Fix redundant so file pack into jar file.
Already pass TPC-H q1~q5 testing on the local server with below two compile commands.
1. mvn clean package -Dbuild_arrow=ON -Dbuild_protobuf=ON -Dbuild_jemalloc=OFF -Dcpp_tests=OFF -Dcheck -DskipTests -Pfull-scala-compiler
2. mvn clean package -Dbuild_arrow=OFF -Dbuild_protobuf=OFF -Dbuild_jemalloc=OFF -Dcpp_tests=OFF -Dcheck -DskipTests -Pfull-scala-compiler

[NSE-254]Fix redundant arrow library issue.

---

native-sql-engine/core/pom.xml

native sql engine is bundled with arrow data source now so
it should be safe to assume those dataset related class will
be 'pre-loaded'
with this fix the jar size is ~97MB(was ~147MB) on my local env

[NSE-254] remove arrow-data-source-common from jar with dependency

---

native-sql-engine/cpp/src/codegen/arrow_compute/ext/actions_impl.cc

Fix missing is_empty value
cherry-picked from https://github.com/oap-project/gazelle_plugin/pull/447/commits/bff3bf8779e0f5552f9d80260c9ad94d52fa5445

[NSE-460] fix decimal partial sum in 1.2 branch

---

arrow-data-source/common/src/main/java/com/intel/oap/spark/sql/execution/datasources/v2/arrow/SparkManagedReservationListener.java
arrow-data-source/common/src/main/scala/org/apache/spark/sql/execution/datasources/v2/arrow/SparkMemoryUtils.scala

[NSE-481] JVM heap memory leak on memory leak tracker facilities

---

native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarWindowExec.scala

This patch restore the coalescebatches before window so the "empty partitions" were removed

[NSE-475] restore coalescebatches operator before window

---

arrow-data-source/common/src/main/scala/org/apache/spark/sql/execution/datasources/v2/arrow/SparkMemoryUtils.scala
arrow-data-source/standard/src/test/scala/com/intel/oap/spark/sql/execution/datasources/arrow/ArrowDataSourceTest.scala
native-sql-engine/core/src/main/java/com/intel/oap/vectorized/ArrowRecordBatchBuilderImpl.java
native-sql-engine/core/src/main/scala/org/apache/spark/sql/execution/python/ColumnarArrowPythonRunner.scala
native-sql-engine/core/src/main/scala/org/apache/spark/sql/util/ArrowUtils.scala
native-sql-engine/core/src/test/scala/com/intel/oap/tpc/ds/TPCDSSuite.scala

[NSE-465] POC release memory using GC

---

native-sql-engine/cpp/src/codegen/arrow_compute/ext/array_appender.h
native-sql-engine/cpp/src/codegen/arrow_compute/ext/array_taker.h
native-sql-engine/cpp/src/codegen/arrow_compute/ext/sort_kernel.cc
native-sql-engine/cpp/src/precompile/array.h

This pr optimized the sort materialization process.
fixed https://github.com/oap-project/gazelle_plugin/issues/479
verified on TPC-DS v1/v2

[NSE-479] optimize sort materialization

---

native-sql-engine/core/src/main/java/com/intel/oap/vectorized/ArrowColumnarToRowInfo.java
native-sql-engine/core/src/main/java/com/intel/oap/vectorized/ArrowColumnarToRowJniWrapper.java
native-sql-engine/core/src/main/scala/com/intel/oap/execution/ArrowColumnarToRowExec.scala
native-sql-engine/cpp/src/benchmarks/columnar_to_row_converter_benchmark.cc
native-sql-engine/cpp/src/jni/jni_wrapper.cc
native-sql-engine/cpp/src/operators/columnar_to_row_converter.cc
native-sql-engine/cpp/src/operators/columnar_to_row_converter.h
native-sql-engine/cpp/src/tests/columnar_to_row_converter_test.cc

[NSE-514] Fix the core dump issue in Q93 with V2 test

---

native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarBroadcastHashJoinExec.scala
native-sql-engine/core/src/main/scala/org/apache/spark/sql/execution/ColumnarCollapseCodegenStages.scala

Next: add the new fix for failed UT
https://github.com/oap-project/gazelle_plugin/issues/207
under test

[NSE-207] improve the fix for join optimization

---

arrow-data-source/common/src/main/java/com/intel/oap/vectorized/ArrowWritableColumnVector.java
arrow-data-source/standard/src/test/scala/com/intel/oap/spark/sql/execution/datasources/arrow/ArrowDataSourceTest.scala
native-sql-engine/core/src/main/scala/com/intel/oap/GazellePluginConfig.scala

Depending on https://github.com/oap-project/arrow/pull/43

[NSE-352] Map/Array/Struct type support for Parquet reading in ArrowData Source

---

native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarBinaryOperator.scala

https://github.com/oap-project/gazelle_plugin/issues/207
verified on UT and V1

[NSE-207] change the fallback condition for Columnar Like

---

arrow-data-source/script/build_arrow.sh
native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarHashAggregateExec.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarExpressionConverter.scala

This patch fixes the subquery reusing. The issue seems introduced by hashagg code change
Note this patch also removed the columnar subquery expression support.

[NSE-540] enable reuse subquery

---

native-sql-engine/core/src/main/java/com/intel/oap/vectorized/BatchIterator.java
native-sql-engine/core/src/main/java/com/intel/oap/vectorized/ExpressionEvaluator.java
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarConditionProjector.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarFilter.scala
native-sql-engine/cpp/src/jni/jni_wrapper.cc

This patch allows to use bigger batch size
closes: #555 

[NSE-555] using 32bit selection vector

---

native-sql-engine/core/src/main/scala/com/intel/oap/GazellePluginConfig.scala
native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarBasicPhysicalOperators.scala
native-sql-engine/core/src/main/scala/com/intel/oap/extension/ColumnarOverrides.scala
native-sql-engine/core/src/main/scala/com/intel/oap/extension/columnar/ColumnarGuardRule.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/streaming/StreamSuite.scala

This patch implements columnar Limit
local unit tests

[NSE-574]implement columnar limit

---

README.md
arrow-data-source/README.md

This patch update doc on data source, adding example on ORC/Parquet v1 data source
closes: #580 

[NSE-580] update doc on data source(DS V1/V2 usage)

---

native-sql-engine/core/src/main/java/com/intel/oap/vectorized/SplitResult.java
native-sql-engine/core/src/main/scala/com/intel/oap/GazellePlugin.scala
native-sql-engine/core/src/main/scala/com/intel/oap/GazellePluginConfig.scala
native-sql-engine/core/src/main/scala/com/intel/oap/extension/ColumnarOverrides.scala
native-sql-engine/core/src/main/scala/org/apache/spark/shuffle/ColumnarShuffleWriter.scala
native-sql-engine/core/src/main/scala/org/apache/spark/util/ShufflePartitionUtils.scala
native-sql-engine/core/src/test/scala/com/intel/oap/misc/PartitioningSuite.scala
native-sql-engine/core/src/test/scala/com/intel/oap/tpc/ds/TPCDSSuite.scala
native-sql-engine/cpp/src/jni/jni_wrapper.cc
native-sql-engine/cpp/src/shuffle/splitter.cc
native-sql-engine/cpp/src/shuffle/splitter.h

Involve in AQE execution to tune against SHJ input partitions to avoid memory leaks.

[NSE-537] Increase partition number adaptively for large SHJ stages 

---

arrow-data-source/common/src/main/java/com/intel/oap/spark/sql/execution/datasources/v2/arrow/SparkManagedAllocationListener.java
arrow-data-source/common/src/main/scala/org/apache/spark/sql/execution/datasources/v2/arrow/SparkMemoryUtils.scala
native-sql-engine/core/src/main/java/com/intel/oap/datasource/parquet/ParquetReader.java
native-sql-engine/core/src/main/java/com/intel/oap/vectorized/BatchIterator.java
native-sql-engine/core/src/main/java/com/intel/oap/vectorized/ExpressionEvaluator.java
native-sql-engine/core/src/main/scala/com/intel/oap/vectorized/ArrowColumnarBatchSerializer.scala
native-sql-engine/core/src/test/scala/com/intel/oap/misc/PartitioningSuite.scala
native-sql-engine/core/src/test/scala/com/intel/oap/tpc/ds/TPCDSSuite.scala

To fix #569 
TPC-H benchmark on Jenkins

[NSE-569] CPU overhead on fine grain / concurrent off-heap acquire operations

---

native-sql-engine/core/src/main/java/com/intel/oap/vectorized/ShuffleSplitterJniWrapper.java
native-sql-engine/core/src/main/scala/com/intel/oap/GazellePluginConfig.scala
native-sql-engine/core/src/main/scala/org/apache/spark/shuffle/ColumnarShuffleWriter.scala
native-sql-engine/cpp/src/jni/jni_wrapper.cc
native-sql-engine/cpp/src/shuffle/splitter.cc
native-sql-engine/cpp/src/shuffle/splitter.h
native-sql-engine/cpp/src/shuffle/type.h

Previously we preallocate memory during split operation for each column and each reducer. the size is controlled by record batch size. It doesn't scale if we use larger record batch, larger shuffle.partitions or more columns to shuffle.
we added a config to set the preallocated size and differ it from record batch size. In the code, we control the maximal memory allocated as 1/4 of total task offheap memory.
tested on single node.

[NSE-588] config the pre-allocated memory for shuffle's splitter

---

native-sql-engine/core/src/main/scala/org/apache/spark/sql/execution/ColumnarShuffleExchangeExec.scala

This patch disabled colummnar shuffle on array/map/struct

[NSE-602] don't enable columnar shuffle on unsupported data types

---

arrow-data-source/script/build_arrow.sh
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarDateTimeExpressions.scala

This patch depends on https://github.com/oap-project/arrow/pull/56.

[NSE-576] Support from_unixtime expression in the case that 'yyyyMMdd' format is required

---

arrow-data-source/script/build_arrow.sh
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarBinaryExpression.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarDateTimeExpressions.scala
native-sql-engine/core/src/test/scala/com/intel/oap/misc/DateTimeSuite.scala

In spark, to_date(string [, fmt]) is used to parse a string to DateType according to given format or default format.
There is no dedicated expression for to_date in vanilla spark. 
1) If fmt is not given, spark will cast string to DateType by corresponding cast expression, which is already supported in gazelle.
2) If fmt is given, spark will firstly use GetTimestamp expression to get timestamp (TimestampType) from the string, then cast the TimestampType to DateType. For this case, we proposed this patch to support it. Currently, only "yyyy-MM-dd" format is supported, otherwise, it will fallback to vanilla spark's execution path.

[NSE-609] Complete to_date expression support

---

native-sql-engine/cpp/src/codegen/arrow_compute/ext/codegen_common.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/kernels_ext.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/merge_join_kernel.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/probe_kernel.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/sort_kernel.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/whole_stage_codegen_kernel.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/window_kernel.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/window_sort_kernel.h
native-sql-engine/cpp/src/jni/jni_wrapper.cc
native-sql-engine/cpp/src/utils/exception.h
native-sql-engine/cpp/src/utils/macros.h

improve codegen failure handling

[NSE-629] improve codegen failure handling

---

native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarSortExec.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarSorter.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ConverterUtils.scala

This is a regression issue caused by the fixing in #601.
For columnar sort, we set `skipAlias` to `true` in all pieces of code that ConverterUtils.getAttrFromExpr() is involved.

[NSE-601] Fix an issue in the case of group by coalesce

---

native-sql-engine/cpp/src/CMakeLists.txt
native-sql-engine/cpp/src/codegen/arrow_compute/ext/codegen_common.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/conditioned_merge_join_kernel.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/conditioned_probe_kernel.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/hash_aggregate_kernel.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/merge_join_kernel.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/sort_kernel.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/whole_stage_codegen_kernel.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/window_sort_kernel.h
native-sql-engine/cpp/src/precompile/wscgapi.hpp

This patch adds a new codegen header (wscgapi.hpp) to simplify the headers used in all codegen
in the first codegen, it will try to compile wscgapi.hpp into pre-compiled header, and reuse this in the following codegen
on my local tests this could speed up the codegen for 1 seconds (2.5s -> 1.5s)

[NSE-126] improve codegen with pre-compiled header

---

native-sql-engine/core/src/test/scala/com/intel/oap/misc/PartitioningSuite.scala
native-sql-engine/core/src/test/scala/com/intel/oap/tpc/ds/Orc_TPCDSSuite.scala
native-sql-engine/core/src/test/scala/com/intel/oap/tpc/ds/TPCDSSuite.scala
native-sql-engine/core/src/test/scala/com/intel/oap/tpc/h/Orc_TPCHSuite.scala
native-sql-engine/core/src/test/scala/com/intel/oap/tpc/h/TPCHSuite.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/CTEHintSuite.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/CharVarcharTestSuite.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/JoinHintSuite.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/SparkSessionBuilderSuite.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/execution/adaptive/AdaptiveQueryExecSuite.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/execution/adaptive/ColumnarAdaptiveQueryExecSuite.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/execution/datasources/csv/CSVSuite.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/execution/datasources/v2/jdbc/JDBCTableCatalogSuite.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/internal/SQLConfSuite.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/nativesql/NativeColumnarAdaptiveQueryExecSuite.scala

Remove all directly use log4j unit tests and import log4j cases.
Tested in local server with mvn clean package & mvn test commands

[NSE-636]Remove log4j1 related unit tests

---

native-sql-engine/cpp/src/codegen/arrow_compute/ext/kernels_ext.h
native-sql-engine/cpp/src/codegen/arrow_compute/ext/window_kernel.cc

fix window output with string array
pass jenkins

[NSE-660] fix window builder with string

---

pom.xml

Change the default hadoop version to 3.2 if not set during compile
Pass test in local develop server.

[NSE-651]Use Hadoop 3.2 as default hadoop.version

---

native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarBinaryExpression.scala
native-sql-engine/cpp/src/codegen/arrow_compute/ext/expression_codegen_visitor.cc

This expression will return the index (1-based) of the first occurrence of given substr in str. And 0 will be returned if the given substr is not contained. Gandiva already has a native implementation for it.

[NSE-675] Add instr expression support

---

native-sql-engine/core/src/main/java/com/intel/oap/vectorized/ArrowRowToColumnarJniWrapper.java
native-sql-engine/core/src/main/scala/com/intel/oap/GazellePluginConfig.scala
native-sql-engine/core/src/main/scala/com/intel/oap/execution/ArrowRowToColumnarExec.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarBinaryExpression.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarExpressionConverter.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarTernaryOperator.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarUnaryOperator.scala
native-sql-engine/core/src/main/scala/com/intel/oap/extension/ColumnarOverrides.scala
native-sql-engine/core/src/test/scala/com/intel/oap/execution/ArrowRowToColumnarExecSuite.scala
native-sql-engine/cpp/src/CMakeLists.txt
native-sql-engine/cpp/src/codegen/arrow_compute/ext/expression_codegen_visitor.cc
native-sql-engine/cpp/src/jni/jni_wrapper.cc
native-sql-engine/cpp/src/operators/row_to_columnar_converter.cc
native-sql-engine/cpp/src/operators/row_to_columnar_converter.h
native-sql-engine/cpp/src/precompile/gandiva.h
native-sql-engine/cpp/src/shuffle/splitter.cc
native-sql-engine/cpp/src/shuffle/splitter.h
native-sql-engine/cpp/src/shuffle/type.h
pom.xml

backport recent patches to 1.3 branch
pass Jenkins

[NSE-667] backport patches to 1.3 branch

---

native-sql-engine/core/src/test/scala/org/apache/spark/sql/execution/columnar/InMemoryColumnarQuerySuite.scala
native-sql-engine/cpp/src/operators/row_to_columnar_converter.cc

Fix the bug for negative decimal data
in arrow all the unused bits should be set to 255. 
pass jenkins

[NSE-400] Fix the bug for negative decimal data

---

.github/workflows/unittests.yml
pom.xml

1. Exclude spark core's log4j library in pom.xml
Closed #687 
2. Add script to remove the exclude for mvn test support
Compile will pass after adding -DskipTests
If the developers need to run unit test, they must remove the exclude code in the pom

[NSE-687]remove exclude log4j when running ut

---

native-sql-engine/core/src/main/scala/org/apache/spark/sql/execution/ColumnarShuffleExchangeExec.scala
native-sql-engine/cpp/src/shuffle/splitter.cc
native-sql-engine/cpp/src/tests/shuffle_split_test.cc

Fix Array type shuffle split segmentation fault for #602 
pass jenkins

[NSE-602] Fix Array type shuffle split segmentation fault

---

native-sql-engine/core/src/main/scala/com/intel/oap/execution/ArrowRowToColumnarExec.scala
native-sql-engine/core/src/main/scala/com/intel/oap/extension/ColumnarOverrides.scala

This pr added the fallback logic for R2C.
Fixed https://github.com/oap-project/gazelle_plugin/issues/705.

[NSE-705] Fallback R2C on unsupported cases

---

native-sql-engine/cpp/src/codegen/arrow_compute/ext/hash_aggregate_kernel.cc
native-sql-engine/cpp/src/precompile/hash_map.cc
native-sql-engine/cpp/src/precompile/unsafe_array.h
native-sql-engine/cpp/src/third_party/parallel_hashmap/btree.h
native-sql-engine/cpp/src/third_party/parallel_hashmap/conanfile.py
native-sql-engine/cpp/src/third_party/parallel_hashmap/meminfo.h
native-sql-engine/cpp/src/third_party/parallel_hashmap/phmap.h
native-sql-engine/cpp/src/third_party/parallel_hashmap/phmap_base.h
native-sql-engine/cpp/src/third_party/parallel_hashmap/phmap_bits.h
native-sql-engine/cpp/src/third_party/parallel_hashmap/phmap_config.h
native-sql-engine/cpp/src/third_party/parallel_hashmap/phmap_dump.h
native-sql-engine/cpp/src/third_party/parallel_hashmap/phmap_fwd_decl.h
native-sql-engine/cpp/src/third_party/parallel_hashmap/phmap_utils.h
native-sql-engine/cpp/src/third_party/row_wise_memory/unsafe_row.h
native-sql-engine/cpp/src/third_party/sparsehash/sparse_hash_map.h

instead of do all agg per row, this patch changed the behavior to do one agg
per column to achieve better cache efficiency
in my local test TPCH Q1 is improved 10%
This patch also optimized the code path for null/nonull hashagg
pass jenkins

[NSE-610] hashagg opt#1

---

native-sql-engine/cpp/src/codegen/arrow_compute/ext/actions_impl.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/hash_aggregate_kernel.cc
native-sql-engine/cpp/src/jni/jni_common.h
native-sql-engine/cpp/src/precompile/hash_map.cc
native-sql-engine/cpp/src/precompile/hash_map.h
native-sql-engine/cpp/src/tests/test_utils.h
native-sql-engine/cpp/src/third_party/sparsehash/sparse_hash_map.h

clean up code path for hashagg with multiple keys
- the big loop should be as tight as possbile
-  remove the redundant lookup logic in hashmap
pass jenkins

[NSE-610] hashagg opt#2

---

native-sql-engine/cpp/src/codegen/arrow_compute/ext/expression_codegen_visitor.cc

It seems runtime_error is out of the scope of logical error in the casting. Let me double think whether that exception should be caught also.

[NSE-740] Catch out_of_range exception in casting string to numeric types in wscg

---

arrow-data-source/common/src/main/java/com/intel/oap/vectorized/ArrowWritableColumnVector.java
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ConverterUtils.scala
native-sql-engine/core/src/main/scala/org/apache/spark/sql/execution/ColumnarShuffleExchangeExec.scala
native-sql-engine/core/src/test/scala/org/apache/spark/shuffle/ColumnarShuffleSQLSuite.scala
native-sql-engine/cpp/src/jni/jni_common.h
native-sql-engine/cpp/src/shuffle/splitter.cc
native-sql-engine/cpp/src/shuffle/utils.h
native-sql-engine/cpp/src/tests/jniutils_test.cc
native-sql-engine/cpp/src/tests/shuffle_split_test.cc

- Support nested Struct in shuffle
Let's focus on Struct support firstly. Because there are many points needed to modify for one new complex type.

[NSE-732] Support Struct complex type in Shuffle

---

native-sql-engine/core/src/main/scala/com/intel/oap/GazellePluginConfig.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarBinaryExpression.scala
native-sql-engine/cpp/src/codegen/arrow_compute/ext/conditioned_probe_kernel.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/hash_relation_kernel.cc

- remove dead code
- sperate code path for single/multi keys join
pass jenkins

[NSE-610] hashjoin opt1

---

native-sql-engine/core/src/main/scala/org/apache/spark/util/ExecutorManager.scala

Change the code style for ExecutorManager
origin tests

[NSE-725] change the code style for ExecutorManger

---

native-sql-engine/core/src/main/scala/com/intel/oap/execution/ArrowRowToColumnarExec.scala
native-sql-engine/cpp/src/codegen/arrow_compute/ext/hash_relation_kernel.cc

This patch tries to remove the hard-coded memory allocation in r2c
pass jenkins

[NSE-746]Fix memory allocation in row to columnar

---

shims/spark311/src/main/scala/com/intel/oap/sql/shims/spark311/SparkShimProvider.scala

With this patch, the runtime checking for spark 3.1.2 & 3.1.3 will also pass.

[NSE-759] Add spark 3.1.2 & 3.1.3 as supported versions for 3.1.1 shim layer

---

native-sql-engine/core/src/main/scala/com/intel/oap/GazellePluginConfig.scala
native-sql-engine/core/src/main/scala/com/intel/oap/extension/ColumnarOverrides.scala
native-sql-engine/core/src/main/scala/org/apache/spark/sql/execution/ColumnarShuffleExchangeExec.scala

Adding new config to enable/disable complex data type support 
pass jenkins

[NSE-732]Adding new config to enable/disable complex data type support 

---

native-sql-engine/core/src/main/scala/com/intel/oap/extension/ColumnarOverrides.scala

fallback Sort after SortHashAgg
pass jenkins

[NSE-784] fallback Sort after SortHashAgg

---

arrow-data-source/common/src/main/java/com/intel/oap/vectorized/ArrowWritableColumnVector.java
arrow-data-source/common/src/main/scala/com/intel/oap/sql/execution/RowToArrowColumnarExec.scala
native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarSortExec.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarSorter.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ConverterUtils.scala
native-sql-engine/core/src/main/scala/com/intel/oap/extension/ColumnarOverrides.scala
native-sql-engine/core/src/test/scala/com/intel/oap/execution/PayloadSuite.scala
native-sql-engine/core/src/test/scala/org/apache/spark/shuffle/ColumnarShuffleSQLSuite.scala
native-sql-engine/cpp/src/codegen/arrow_compute/ext/array_taker.h
native-sql-engine/cpp/src/tests/arrow_compute_test_sort.cc

Now Array/Struct/Map all supported.

[NSE-762] Add complex types support for ColumnarSortExec

---

native-sql-engine/core/src/main/scala/com/intel/oap/extension/ColumnarOverrides.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/execution/adaptive/AdaptiveQueryExecSuite.scala

Some commits of #773 have already been merged into branch-1.3.1. This PR cherry-picked the remain commits.

[NSE-774] Fallback broadcast exchange for DPP to reuse

---

native-sql-engine/core/src/test/scala/org/apache/spark/sql/DataFrameStatSuite.scala

[NSE-788] Quick fix for randomSplit on reordered partitions

---

README.md
docs/Installation.md
docs/User-Guide.md

This patch adds example guide on how to enable shim layers
No tests required

[NSE-786] Adding docs for shim layers

---

native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarHashAggregateExec.scala

Fix count() with decimal value
closes: #794 
pass jenkins

[NSE-794] Fix count() with decimal value

---

native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarHashAggregateExec.scala
native-sql-engine/core/src/main/scala/com/intel/oap/extension/ColumnarOverrides.scala
shims/spark321/src/main/scala/org/apache/spark/sql/execution/adaptive/AdaptiveSparkPlanExec.scala

backport from master to 1.3.1 branch
pass jenkins

[NSE-782]  backport master changes to 1.3.1 branch

---

native-sql-engine/core/src/main/scala/org/apache/spark/sql/execution/ColumnarCollapseCodegenStages.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/execution/adaptive/AdaptiveQueryExecSuite.scala

It is not supported to have two or more SMJ consecutively executed in a whole stage code gen.

[NSE-795] Fix a consecutive SMJ issue in wscg

---

native-sql-engine/core/src/main/java/com/intel/oap/vectorized/JniUtils.java

We may load wrong include files while calling `JniUtils.loadIncludeFromJar`, espetially when there is another jar has `include` resouces. Thus this pr try to solve this problem by loading the include file inside of the jar that contains JniUtils.class
Unit tests

[NSE-778] Failed to find include file while running code gen

---

native-sql-engine/core/src/main/scala/org/apache/spark/sql/execution/ColumnarCollapseCodegenStages.scala

This patch fixes wholestage codegen on unsupported pattern.
The issue is introduced by a variant LeftOuter SortMergeJoin
with Projection as its right child, which breaks the codegen
depedency pattern.
This patch introduced a check on this pattern and stop doing
codegen under this case.
pass jenkins

[NSE-821] Fix Wholestage Codegen on unsupported pattern

---

native-sql-engine/core/src/test/scala/org/apache/spark/sql/execution/SortSuite.scala
native-sql-engine/cpp/src/codegen/arrow_compute/ext/hash_relation_kernel.cc
native-sql-engine/cpp/src/codegen/common/hash_relation.h
native-sql-engine/cpp/src/third_party/row_wise_memory/hashMap.h

This patch addes shrink on hashmap after the map is built.
This patch also increased the memory limit for hashmap.
pass jenkins

[NSE-610] Shrink hashmap to use less memory

---

native-sql-engine/core/src/main/scala/com/intel/oap/execution/ArrowRowToColumnarExec.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/execution/SortSuite.scala

This patch improves the memory allocation in r2c by doing
estimation based on first row. Also check the capacity during
the conversation and increase the buffer size if not enough
pass jenkins

[NSE-746]Fix memory allocation in row to columnar 

---

arrow-data-source/script/build_arrow.sh
native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarBroadcastHashJoinExec.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarBinaryOperator.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarExpressionConverter.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarRegexp.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarTernaryOperator.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarUnaryOperator.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/FileBasedDataSourceSuite.scala

Support expressions like length, char_length, locate, regexp_extract.
Some spark unit tests covers these expressions. A unit test suite is added in gandiva for testing regexp_extract.

[NSE-818] Support length, char_length, locate & regexp_extract

---

arrow-data-source/script/build_arrow.sh
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarExpressionConverter.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarTernaryOperator.scala

Add substring_index function support.
Unit tests/ workload tests.

[NSE-867] Add substring_index function support

---

native-sql-engine/core/src/main/scala/com/intel/oap/GazellePluginConfig.scala
native-sql-engine/core/src/main/scala/com/intel/oap/extension/ColumnarOverrides.scala
native-sql-engine/core/src/main/scala/org/apache/spark/sql/execution/ColumnarCollapseCodegenStages.scala

In case of queries with small shuffle size the elapsed time is increased when running with gazelle. One option for improvement is to skip the wholestagegencode step for such queries. This PR add the option to use such feature by enabling the flag
"spark.oap.sql.columnar.shuffleThresholdEnabled" and setting the shuffle size threshold for small shuffles "spark.oap.sql.columnar.shuffleThreshold". 
When a small shuffle size in detected in a stage an internal flag: 
spark.oap.sql.columnar.codegendisableforsmallshuffles is turned on for the code gen to disabled. 
The flag is turned off at the end of the stage.
Ran TPCDS on Dataproc/GCP
For q2 there was a slight enhancement in performance

[NSE-854] Small Shuffle Size disable wholestagecodegen

---

native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarExpressionConverter.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarTernaryOperator.scala

implement spark replace function.
https://spark.apache.org/docs/latest/api/sql/index.html#replace
Unit tests

[NSE-872] implement replace function

---

arrow-data-source/standard/src/main/scala/com/intel/oap/spark/sql/execution/datasources/arrow/ArrowFileFormat.scala

Fix writing arrow hang with OutputWriter.path.
```
"Executor task launch worker for task 0.0 in stage 2.0 (TID 2)" #182 daemon prio=5 os_prio=0 tid=0x00007fe734024000 nid=0x573c runnable [0x00007fe50cfe3000]
java.lang.Thread.State: RUNNABLE
at com.intel.oap.spark.sql.execution.datasources.arrow.ArrowFileFormat$$anon$1$$anon$2.path(ArrowFileFormat.scala:102)
at org.apache.spark.sql.execution.datasources.SingleDirectoryDataWriter.$anonfun$write$2(FileFormatDataWriter.scala:176)
at org.apache.spark.sql.execution.datasources.SingleDirectoryDataWriter.$anonfun$write$2$adapted(FileFormatDataWriter.scala:176)
```
unit tests

[NSE-876] Fix writing arrow hang with OutputWriter.path

---

native-sql-engine/cpp/src/codegen/arrow_compute/ext/codegen_common.cc

This patch adds one more configuration for deployment with jar cmd
not in PATH
export JAR=/path/to/jar
--conf spark.executorEnv.JAR=/path/to/jar
Pass jenkins

[NSE-892] Allow to use jar cmd not in PATH

---

arrow-data-source/common/src/main/scala/com/intel/oap/spark/sql/ArrowWriteQueue.scala

When spark speculation is true, the FinalTask may be killed as another attempt succeeded. In this case, DatasetFileWriter may failed and threw exception, which will cause executor failed.
unit test

[NSE-891] Spark executor lost while DatasetFileWriter failed with speculation

---

native-sql-engine/cpp/src/shuffle/splitter.cc

fix bug of PR903. Check the nullptr before setting

[NSE-910] fix bug of PR903

---

native-sql-engine/cpp/src/shuffle/splitter.cc
native-sql-engine/cpp/src/shuffle/splitter.h

Previous implementation of validity buffer split performance is too bad.
<table>
<tr>
<td> no validity buffer
<td> 1.55
<tr>
<td> w/ validity buffer, before opt
<td> 2.51
<tr>
<td>w/ validity buffer, after opt
<td> 2.01
</table>
From profile data, validity buffer split still takes more time than value copy. Most of the time is spending on the first touch of dst buffer
```
67.32%  BenchmarkShuffl  libspark_columnar_jni.so  [.] sparkcolumnarplugin::shuffle::Splitter::SplitBoolType                                                                              
25.96%  BenchmarkShuffl  libspark_columnar_jni.so  [.] sparkcolumnarplugin::shuffle::Splitter::SplitFixedWidthValueBuffer                                                                 
1.81%  BenchmarkShuffl  libspark_columnar_jni.so …
```

[NSE-857] Further optimizations of validity buffer split

---

native-sql-engine/cpp/CMakeLists.txt
native-sql-engine/cpp/src/benchmarks/shuffle_split_benchmark.cc
native-sql-engine/cpp/src/shuffle/splitter.cc
native-sql-engine/cpp/src/shuffle/splitter.h
native-sql-engine/cpp/src/tests/shuffle_split_test.cc

manually split the string/binary column. 
Previously we use builder to construct the string buffer. The PR create the destination buffers and read the src buffers, then split the column manually
The PR also removed some unused code

[NSE-856] Optimize of string/binary split

---

arrow-data-source/common/src/main/java/com/intel/oap/vectorized/ArrowColumnVectorUtils.java
arrow-data-source/common/src/main/java/com/intel/oap/vectorized/ArrowWritableColumnVector.java
arrow-data-source/standard/src/main/scala/com/intel/oap/spark/sql/execution/datasources/v2/arrow/ArrowUtils.scala

We are using setSafe to put partitionValues to Vectors while calling buildReaderWithPartitionValues. As showing in bellow image, it cost 11% cpu time to check handleSafe.
Actually, the partitionValues written are all fixed length, so we can handleSafe once before writing into arrow, and use Vector.set instead of Vector.setSafe to remove extra handleSafe costs.
Unit tests

[NSE-912] Remove extra handleSafe costs

---

arrow-data-source/script/build_arrow.sh
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarLiterals.scala

This patch adds the missing type in ColumnarLiterals
pass jenkins

[NSE-581] adding ShortType/FloatType in ColumnarLiteral

---

native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarBinaryOperator.scala

This patch implements rlike/regexp_like
pass jenkins

[NSE-581] implement rlike/regexp_like

---

arrow-data-source/common/src/main/scala/com/intel/oap/sql/execution/RowToArrowColumnarExec.scala
native-sql-engine/core/src/main/scala/com/intel/oap/execution/ArrowCoalesceBatchesExec.scala
native-sql-engine/core/src/main/scala/com/intel/oap/execution/ArrowRowToColumnarExec.scala

[NSE-958] Fix SQLMetrics inaccuracy in JVM/Native R2C and CoalesceBatcth

---

arrow-data-source/script/build_arrow.sh
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarExpressionConverter.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarTernaryOperator.scala

Support expression conv to convert number represented by string from one base to another.
UT.

[NSE-955] Support expression conv

---

arrow-data-source/script/build_arrow.sh
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarConcatOperator.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarExpressionConverter.scala

This patch implements concat_ws
pass jenkins

[NSE-955] implement concat_ws

---

arrow-data-source/script/build_arrow.sh
native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarSortMergeJoinExec.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarExpressionConverter.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarInOperator.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarTernaryOperator.scala

This patch implements lpad/rpad
pass jenkins

[NSE-955] implement lpad/rpad

---

native-sql-engine/cpp/src/CMakeLists.txt
native-sql-engine/cpp/src/operators/columnar_to_row_converter.cc
native-sql-engine/cpp/src/shuffle/splitter.cc

[NSE-927] Add macro __AVX512BW__ check for different CPU architecture

---

native-sql-engine/cpp/src/codegen/arrow_compute/ext/codegen_common.cc

this patch sets default codegen opt level to O1, to reduce the codegen overhead
pass jenkins

[NSE-126] set default codegen opt to O1

---

arrow-data-source/common/src/main/scala/org/apache/spark/sql/execution/datasources/v2/arrow/SparkSchemaUtils.scala
arrow-data-source/standard/src/main/scala/com/intel/oap/spark/sql/execution/datasources/arrow/ArrowFileFormat.scala
arrow-data-source/standard/src/main/scala/com/intel/oap/spark/sql/execution/datasources/v2/arrow/ArrowFilters.scala
arrow-data-source/standard/src/main/scala/com/intel/oap/spark/sql/execution/datasources/v2/arrow/ArrowPartitionReaderFactory.scala
arrow-data-source/standard/src/main/scala/com/intel/oap/spark/sql/execution/datasources/v2/arrow/ArrowUtils.scala
arrow-data-source/standard/src/test/scala/com/intel/oap/spark/sql/execution/datasources/arrow/ArrowDataSourceTest.scala

This PR is trying to fix the problem with reading parquet with case sensitive column names. In our scenarios, we have case sensitive column names in parquet, such as `Id7`, and scan parquet with case insensitive mode, which means `id7` whill be pushed down to source, and then we will get 'Id7 not exists'.
unit tests and additional test.

[NSE-979] Support reading parquet with case sensitive

---

native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarHashAggregateExec.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarBinaryOperator.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarCaseWhenOperator.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarUnaryOperator.scala

This patch adds extra check in HashAgg so unsupported expressions/attributes will fallback
pass jenkins

[NSE-981] check all expressions in HashAgg

---

native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarConcatOperator.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarExpressionConverter.scala

This patch fixes concat_ws bug with only two params
pass jenkins

[NSE-984] fix concat_ws

---

native-sql-engine/cpp/src/codegen/arrow_compute/ext/array_item_index.h
native-sql-engine/cpp/src/codegen/arrow_compute/ext/sort_kernel.cc
native-sql-engine/cpp/src/shuffle/splitter.cc

- ARROW_CHECK for batch_size  per Recordbatch
- ARROW_CHECK for Recordbatch's number

[NSE-928] Add ARROW_CHECK for batch_size check

---

native-sql-engine/cpp/src/operators/row_to_columnar_converter.cc
native-sql-engine/cpp/src/operators/row_to_columnar_converter.h

- Use Arrow buffer instead of Arrow Builder
- Use AVX-512 
- Merge Binary case into String case
- Initializing the validity buffer with "ture".

[NSE-943] Optimize data conversion for String/Binary type in Row2Columnar

---

gazelle-dist/src/main/assembly/assembly.xml

This patch will avoid trying to include the artifact for gazelle-dist module in the assembly. Thus, the below build warning can be fixed:
`[WARNING] Cannot include project artifact: com.intel.oap:gazelle-dist:pom:1.4.0-SNAPSHOT; it doesn't have an associated file or directory.`

[NSE-800] Fix an assembly warning

---

tests/udf/README.md
tests/udf/src/com/intel/oap/URLDecoderNew.java

A new directory called `tests` is created under the root of the repo. It will contain test guide, script and useful source code for functionality testing.
The `tests` folder will not be built and also will not be included in deployment jar.

[NSE-1007] Add a test guide for columnar UDF

---

native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarExpressionConverter.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarHashExpression.scala

This is for spark function named "hash" to get the murmur3 hash result for a given input.
UT.

[NSE-955] Add Murmur3Hash expression support

---

native-sql-engine/cpp/src/codegen/arrow_compute/ext/sort_kernel.cc
native-sql-engine/cpp/src/third_party/row_wise_memory/unsafe_row.h
native-sql-engine/cpp/src/third_party/timsort.hpp

using string_view instead of std::string remove the string construct overhead
pass jenkins

[NSE-999] s/string/string_view in sort

---

.github/workflows/unittests.yml
native-sql-engine/cpp/src/codegen/arrow_compute/ext/sort_kernel.cc
native-sql-engine/cpp/src/tests/arrow_compute_test_externalsort.cc
native-sql-engine/cpp/src/tests/arrow_compute_test_sort.cc
native-sql-engine/cpp/src/tests/jniutils_test.cc

This patch replace std::sort() with Timsort() on onekey string/decimal cases
closes: #999 
pass jenkins

[NSE-999] use TimSort for STRING/DECIMAL onekey based sorting

---

native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarWindowExec.scala

We didn't consider Literal type in window functions, espetially while partitioning by Literal in window functions.
Here is an example problem SQL `select col_lit, b, row_number() over (partition by col_lit, a order by int(b) asc) as c
from (select "abc" as col_lit, a, b from test)`.
origin tests

[NSE-1027] Problem with Literal in window function

---

native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarShuffledHashJoinExec.scala

We do a WSCG check in ColumnarShuffledHashJoinExec. But only check the condition, not leftKeys and rightKeys check.
For ExsitingJoin, the condition is null, and there are only leftKeys and rightKeys, which leads to function is currently not supported in WSCG.
unit tests and manual test.

[NSE-1032] Adding WSCG check for keys in Join

---

native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarExpressionConverter.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarTernaryOperator.scala

This pr try to support function in substring's pos and len, such as `select substr(col, 2, length(col) - 2) from table`.
unit test and manual test.

[NSE-1053] Support function in substring's pos and len

---

native-sql-engine/core/src/main/scala/com/intel/oap/execution/ArrowColumnarToRowExec.scala

This patch fixes the memory leakage in columnartorow operator
pass jenkins

[NE-400] fix memory leakage in native columnartorow

---

native-sql-engine/core/src/main/scala/com/intel/oap/GazellePlugin.scala

When we start spark with user spark extension and gazelle, it will throw "Spark extensions are already specified before enabling Gazelle plugin: ". Actually, this exception should only be thrown when user set spark.sql.extensions to GazelleSessionExtensions or ArrowWriteExtension.
unit tests

[NSE-929] Support user defined spark extensions

---

arrow-data-source/script/build_arrow.sh
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarDateTimeExpressions.scala
native-sql-engine/core/src/test/scala/com/intel/oap/misc/DateTimeSuite.scala

[NSE-955] Support more date format in unix timestamp

---

native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarHashAggregateExec.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarHashAggregation.scala
native-sql-engine/cpp/src/codegen/arrow_compute/ext/actions_impl.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/actions_impl.h
native-sql-engine/cpp/src/codegen/arrow_compute/ext/hash_aggregate_kernel.cc

This patch adds support for hashagg w/ filter
pass jenkins

[NSE-1065] Adding hashagg w/ filter support

---

gazelle-dist/pom.xml

spark-arrow-datasource-parquet is experimental and it is used to override spark's ParquetFileFormat. It should be deployed separately by need.

[NSE-800] Remove spark-arrow-datasource-parquet in assembly

---

native-sql-engine/cpp/src/third_party/row_wise_memory/unsafe_row.h

support big hashagg keys. By default the max size of hashagg keys is 8192 bytes, in case this is not enough, it will try to do a re-alloc to 2x8192 bytes
pass jenkins

[NSE-610] support big keys in hashagg

---

native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarBinaryExpression.scala

The wildcard is not commonly used. So we just fall back to vanilla spark for this case.

[NSE-1100] Fall back get_json_object when wildcard is contained in json path

---

native-sql-engine/core/src/test/scala/org/apache/spark/sql/nativesql/NativeSQLConvertedSuite.scala
native-sql-engine/cpp/src/precompile/unsafe_array.h
native-sql-engine/cpp/src/third_party/row_wise_memory/unsafe_row.h

This patch fixes one case of hashagg wrong results over multiple columns
`group by col_a, col_b`
col_a | col_b
-- | --
"ab" | "ab"
"a" | "bab"
"aba" | "b"
"abab" | ""
The fix introduced a new is_empty field to tell whether some columns are empty string, which can fix the issue on last row
new unit tests

[NSE-1104] fix hashagg w/ empty string

---

arrow-data-source/standard/src/main/scala/com/intel/oap/spark/sql/execution/datasources/v2/arrow/ArrowScan.scala
native-sql-engine/core/src/main/scala/com/intel/oap/GazellePluginConfig.scala
native-sql-engine/core/src/main/scala/com/intel/oap/extension/ColumnarOverrides.scala
native-sql-engine/core/src/main/scala/com/intel/oap/extension/StrategyOverrides.scala
native-sql-engine/core/src/main/scala/com/intel/oap/extension/columnar/ColumnarGuardRule.scala
native-sql-engine/core/src/main/scala/org/apache/spark/sql/LocalWindowExec.scala
shims/common/src/main/scala/com/intel/oap/sql/shims/SparkShims.scala
shims/spark311/src/main/scala/com/intel/oap/sql/shims/spark311/Spark311Shims.scala
shims/spark321/src/main/scala/com/intel/oap/sql/shims/spark321/Spark321Shims.scala

Let whole stage fallback if there would be 3 or more fallbacks in a stage.
UT.

[NSE-947] Add a whole stage fallback strategy

---

native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarWindowExec.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarConditionedProbeJoin.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarExpressionConverter.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarHashAggregation.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ConverterUtils.scala

This patch fixes the different cases in column names by converting them to lower case
pass jenkins

[NSE-1108] allow to use different cases in column names

---

native-sql-engine/cpp/src/operators/row_to_columnar_converter.cc

Fix #1112 .
Still not clear why capacity_ of buffer becomed to the value of size_,
but this patch can fix this issue.
pass jenkins

[NSE-1112] Fix Arrow array meta data validating issue when writing parquet files

---

native-sql-engine/core/src/main/scala/com/intel/oap/GazellePluginConfig.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarUDF.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/DataFrameSuite.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/test/SharedSparkSession.scala

We added a config to turn on/off columnar UDF. Currently, only url decoder is the supported UDF. So it will only have an impact on this UDF.
@jackylee-ch, please have a review.

[NSE-1116] Disable columnar url_decoder

---

native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarHashAggregateExec.scala
native-sql-engine/core/src/test/scala/com/intel/oap/tpc/ds/TPCDSSuite.scala

This patch fixes codegen issue on TPCDS Q88
pass jenkins

[NSE-1118] fix codegen on TPCDS Q88

---

native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarWindowExec.scala
native-sql-engine/cpp/src/codegen/arrow_compute/expr_visitor.cc
native-sql-engine/cpp/src/codegen/arrow_compute/expr_visitor_impl.h
native-sql-engine/cpp/src/codegen/arrow_compute/ext/kernels_ext.h
native-sql-engine/cpp/src/codegen/arrow_compute/ext/window_kernel.cc
native-sql-engine/cpp/src/tests/arrow_compute_test_window.cc

Support a window function called lag.
UT/Integration tests.

[NSE-955] Support window function lag

---

native-sql-engine/cpp/src/codegen/arrow_compute/ext/hash_aggregate_kernel.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/kernels_ext.cc
native-sql-engine/cpp/src/codegen/arrow_compute/ext/probe_kernel.cc

Index returns -1 when HashMap.GetOrInsert failed with some problems such as buffer overflow or OOM. And it whould finally core dump when trying to use this index.
Here we add a status check and throw exception if it failed.
unit tests.

[NSE-1125] Add status check for hashing GetOrInsert

---

native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarShuffledHashJoinExec.scala

[NSE-610] fix hashjoin build time metric

---

native-sql-engine/cpp/src/codegen/arrow_compute/ext/hash_aggregate_kernel.cc
native-sql-engine/cpp/src/precompile/hash_map.cc
native-sql-engine/cpp/src/precompile/hash_map.h

Current hash aggegate use `StringHashMap` to build hash table, which actually use `StringBuilder` to storage keys and its size is limited to `Int.max-1`. We meet the problem with `Capacity error: array cannot contain more than 2147483646 bytes, have 2147483708` while using aggeragate, it shows the origin buffer in hash map for hash aggerate is overflowed. 
Thus, we use `LargeStringHashMap` to build hash table, which use `LargeBinaryBuilder` to storage keys and its size is limited to `Long.max-1`.
unit tests.

[NSE-1127] Use larger buffer for hash agg

---

native-sql-engine/core/src/main/java/com/intel/oap/vectorized/JniUtils.java

FileUtils.forceDeleteOnExit won't delete the files that are added after function calls, and it will fail to delete the directory. Thus we add new hook to delete the directory.
unit tests.

[NSE-1114] Remove temp directory without FileUtils.forceDeleteOnExit

---

native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarWindowExec.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/DataFrameWindowFunctionsSuite.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/execution/SQLWindowFunctionSuite.scala
native-sql-engine/cpp/src/codegen/arrow_compute/expr_visitor.cc
native-sql-engine/cpp/src/codegen/arrow_compute/expr_visitor_impl.h
native-sql-engine/cpp/src/codegen/arrow_compute/ext/kernels_ext.h
native-sql-engine/cpp/src/codegen/arrow_compute/ext/window_kernel.cc
native-sql-engine/cpp/src/tests/arrow_compute_test_window.cc

This patch is based on #1056. So we need rebase it after #1056 is merged.

[NSE-1120] Support sum window function with order by statement

---

native-sql-engine/core/src/main/scala/org/apache/spark/sql/execution/ColumnarCollapseCodegenStages.scala

We meet the `RecordBatch must be non-empty` problem when there is a `ColumnarWindowExec` after WSCG and there is a `ColumnarConditionProjectExec` as a child of `ColumnarWindowExec`. It help use when we tried to remove the `ColumnarConditionProjectExec` from WSCG.
unit tests and manual test.

Remove project from wscg when it's the child of window

---

native-sql-engine/cpp/src/codegen/common/relation_column.h

Currently we use ValueOrDie to check the status, such as LazyBatchIterator.AdvanceTo, and it will directly hang up the current process if there is an exception caused bad status. However, in many cases, it is sufficient to just throw an exception rather than hang up the process, such as the FetchFailedException, which means fetch block failed from other executor. And for Spark, the hanging of the executor process is much more serious than throwing exception, because this will lead to a large number of task recalculations, which may lead to more serious problems.
unit tests and manual tests.

[NSE-1141] Replace ValueOrDie with status check to avoid executor die

---

native-sql-engine/cpp/src/codegen/arrow_compute/ext/expression_codegen_visitor.cc
native-sql-engine/cpp/src/precompile/wscgapi.hpp

Currently we use stod or stoi in cast WSCG, and it has a bad behavior while using cast. This patch we are trying to use the implement in arrow to optimize the performance.
unit tests and manual tests.

[NSE-1144] Optimize cast wscg performance

---

native-sql-engine/core/src/main/scala/com/intel/oap/GazellePluginConfig.scala
native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarBasicPhysicalOperators.scala
native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarBroadcastHashJoinExec.scala
native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarHashAggregateExec.scala
native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarShuffledHashJoinExec.scala
native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarSortExec.scala
native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarSortMergeJoinExec.scala
native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarWholeStageCodegenExec.scala

We meet the OOM when there are many columns passed from WSCG. This related to #1137.  This PR is trying to avoid this problem before #1137  fixed.
unit tests.

[NSE-1164] Limit the max column num in WSCG

---

arrow-data-source/parquet/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetSQLConf.scala
arrow-data-source/standard/src/main/scala/com/intel/oap/spark/sql/execution/datasources/v2/arrow/ArrowSQLConf.scala
docs/Configuration.md
native-sql-engine/core/src/main/scala/com/intel/oap/GazellePluginConfig.scala

Reformat SQL config key name from `spark.sql` to `spark.oap.sql` in Gazelle. After this PR, users can easily distinguish between Gazelle-specific Config and Spark Config.
unit tests

[NSE-1161] Format sql config string key

---

native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarHashAggregateExec.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarCoalesceOperator.scala
native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarConcatOperator.scala
native-sql-engine/core/src/main/scala/org/apache/spark/sql/execution/ColumnarCollapseCodegenStages.scala

This patch disabled codegen for concat/coalesce
pass jenkins

[NSE-1156] fix concat codegen

---

arrow-data-source/standard/src/main/scala/com/intel/oap/spark/sql/execution/datasources/v2/arrow/ArrowUtils.scala

This patch fixes the row number in batch scan w/ partition columns
pass jenkins

[NSE-1170] Setting correct row number in batch scan w/ partition columns

---

native-sql-engine/core/pom.xml
native-sql-engine/core/src/test/scala/org/apache/spark/sql/jdbc/JDBCWriteSuite.scala

This patch bumps h2/postsql version
pass jenkins

bump h2/pgsql version

---

.github/workflows/unittests.yml
arrow-data-source/common/src/main/scala/com/intel/oap/spark/sql/ArrowWriteQueue.scala
arrow-data-source/script/build_arrow.sh
arrow-data-source/standard/src/main/scala/com/intel/oap/spark/sql/execution/datasources/arrow/ArrowFileFormat.scala

This patch adds support for writing parquet with compression
`df.coalesce(1).write.format("arrow").option("parquet.compression","zstd").save(path)`
this patch depends on https://github.com/oap-project/arrow/pull/122
pass jenkins

[NSE-956] allow to write parquet with compression

---

arrow-data-source/standard/src/main/scala/com/intel/oap/spark/sql/ArrowConvertExtension.scala
arrow-data-source/standard/src/main/scala/com/intel/oap/spark/sql/execution/datasources/arrow/ArrowFileFormat.scala
native-sql-engine/core/src/main/scala/com/intel/oap/GazellePlugin.scala

In our scenario, users usually read or write hive parquet tables, which different from arrow datasource tables, thus we need a conversion rule to convert `ParquetFileFormat` to `ArrowFileFormat`.
unit tests and we have used it in our scenario.

[NSE-1161] Support read-write parquet conversion to read-write arrow

---

arrow-data-source/script/build_arrow.sh

fix to use right arrow branch
pass jenkins

fix to use right arrow branch

---

arrow-data-source/standard/src/main/scala/com/intel/oap/spark/sql/execution/datasources/arrow/ArrowFileFormat.scala
arrow-data-source/standard/src/main/scala/com/intel/oap/spark/sql/execution/datasources/v2/arrow/ArrowFilters.scala
arrow-data-source/standard/src/main/scala/com/intel/oap/spark/sql/execution/datasources/v2/arrow/ArrowPartitionReaderFactory.scala
arrow-data-source/standard/src/main/scala/com/intel/oap/spark/sql/execution/datasources/v2/arrow/ArrowUtils.scala
arrow-data-source/standard/src/test/scala/com/intel/oap/spark/sql/execution/datasources/arrow/ArrowDataSourceTest.scala

This pr is trying to support Parquet Schema merge in ArrowFileFormat.infer_schema and support dealing with missing column or filter in Parquet reading.
unit tests.

[NSE-1171] Support merge parquet schema and read missing schema

---

pom.xml

Modify Hadoop version in pom.xml from 3.2.2 to 3.2.3 to sync with latest Dataproc 2.0 image's Hadoop version.
And cherry-pick previous commit from branch-1.4 to add support for Hadoop 3.3.1.

[NSE-1185] Add Hadoop version 3.2.3 for latest Dataproc 2.0

---

.github/workflows/tpch.yml
.github/workflows/unittests.yml
arrow-data-source/common/src/main/scala/com/intel/oap/spark/sql/ArrowWriteQueue.scala
arrow-data-source/script/build_arrow.sh
arrow-data-source/standard/src/main/scala/com/intel/oap/spark/sql/ArrowConvertExtension.scala
arrow-data-source/standard/src/main/scala/com/intel/oap/spark/sql/execution/datasources/arrow/ArrowFileFormat.scala
arrow-data-source/standard/src/main/scala/com/intel/oap/spark/sql/execution/datasources/v2/arrow/ArrowFilters.scala
arrow-data-source/standard/src/main/scala/com/intel/oap/spark/sql/execution/datasources/v2/arrow/ArrowPartitionReaderFactory.scala
arrow-data-source/standard/src/main/scala/com/intel/oap/spark/sql/execution/datasources/v2/arrow/ArrowUtils.scala
arrow-data-source/standard/src/test/scala/com/intel/oap/spark/sql/execution/datasources/arrow/ArrowDataSourceTest.scala
native-sql-engine/core/pom.xml
native-sql-engine/core/src/main/scala/com/intel/oap/GazellePlugin.scala
native-sql-engine/core/src/test/scala/org/apache/spark/sql/jdbc/JDBCWriteSuite.scala
native-sql-engine/cpp/src/CMakeLists.txt

This patch backport recent commits to 1.5 branch
pass jenkins

backport recent commits to 1.5 branch

---

native-sql-engine/core/src/main/java/com/intel/oap/vectorized/JniUtils.java
native-sql-engine/core/src/main/scala/org/apache/spark/util/GazelleShutdownManager.scala

unload native libs on spark context exit
pass jenkins

[NSE-1193] fix jni unload

---

native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarConcatOperator.scala

Concat with only one expression is not supported yet. here is a little sample, `select concat(expr) from table`
closes: #1196 
unit tests.

[NSE-1196] Fix: concat with only one expression

---

arrow-data-source/common/src/main/scala/com/intel/oap/spark/sql/FakeRow.scala
arrow-data-source/standard/src/main/scala/com/intel/oap/spark/sql/ArrowWriteExtension.scala
arrow-data-source/standard/src/main/scala/com/intel/oap/spark/sql/execution/datasources/arrow/ArrowFileFormat.scala
shims/spark311/src/main/scala/org/apache/spark/sql/execution/datasources/BaseWriteStatsTracker.scala
shims/spark321/src/main/scala/org/apache/spark/sql/execution/datasources/BaseWriteStatsTracker.scala
shims/spark322/src/main/scala/org/apache/spark/sql/execution/datasources/BaseWriteStatsTracker.scala

Currently, we can only print FakeRow count for write metrics, not the actual writed row count.
unit tests

Print output row count for write command with FakeRow

---

native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarHashAggregateExec.scala

`java.lang.UnsupportedOperationException: PartialMerge is NOT supported for First agg func.!` is thrown in the running of gazelle.
unit tests

[NSE-1202]Check aggregate mode for first func in build check

---

native-sql-engine/core/src/main/scala/org/apache/spark/sql/execution/ColumnarCollapseCodegenStages.scala

It is not expected to return true for existsjoins when there are two HashAggExec.
unit tests.

Avoid WSCG with two HashAgg
